# PAOLA FORABOSCO 28/04/2016

# ============================================================================ #
#  DESCRIPTION
# ============================================================================ #
# This R script processes daily dietary diaries to compute and visualize
# total and weekly mean nutrient intakes for each participant in order to 
# identify extreme outliers (3 × IQR rule).
#
# Workflow:
#   1. Load raw data from "<sample>_data.rda"
#   2. Filter daily diaries (only "Totale" meals and valid collection weeks)
#   3. Compute:
#        - Total mean values per participant  → "<sample>_Diaries_TM.csv"
#        - Weekly mean values per participant → "<sample>_Diaries_WM.csv"
#
# Files generated by this script:
#   CSV files:
#     - "<sample>_Diaries_TM.csv"        : total mean nutrient intakes per participant
#     - "<sample>_Diaries_WM.csv"        : weekly mean nutrient intakes per participant
#
#   Boxplot images (JPEG):
#     - "<sample>__outliers.jpeg"        : total mean boxplots for all traits
#     - "<sample>_<trait>_outliers_per_week.jpeg" : weekly boxplots per trait
#
# Replace <sample> with TRIESTE, CAGLIARI, or BOLOGNA as needed.
#
# -----------------
# Input file format
# -----------------
#
# The dataset DATA, contained in the input file <sample>_data.rda, is derived 
# from the MyFitnessPal app and must contain the following columns 
# (specific column order is not required):
#
#   ID, Pasti, Calorie, Carboidrati, Grassi, Proteine,
#   Colest, Sodio, Zuccheri, Fibre, weeks_raccolta
#
# Description of variables:
# - ID: numeric identifier of the participant.
# - Pasti: meal type (e.g. "Prima colazione", "Pranzo", "Cena", "Snack", "Totale").
# - Calorie, Carboidrati, Grassi, Proteine, Colest, Sodio, Zuccheri, Fibre:
#   nutritional variables recorded for each meal.
# - weeks_raccolta: week of data collection; may be NA if not available.
#
# Each row represents a single meal record for a participant.
# Multiple rows per participant are expected.
# Missing values must be explicitly coded as NA.
#
# This script uses only rows where Pasti == "Totale" and weeks_raccolta is not NA.

# An additional file named "PHENO.csv" is required.
# This file must contain the following columns:
#
# - ID2: participant identifier, formatted with a sample-specific prefix:
#        * "X" for TRIESTE
#        * "S" for CAGLIARI
#        * "B" for BOLOGNA
# - Age: age of the participant.
# - BMI: body mass index of the participant.
#
# The ID2 column is used to merge phenotype information (Age and BMI)
# with the dietary data ID.
                                                           
# ============================================================================ #
#  INITIALIZATION
# ============================================================================ #

# Libraries for plotting, data manipulation, and layout
library(ggrepel)     # Improved placement of text labels
library(ggplot2)     # Core plotting system
library(dplyr)       # Data manipulation
library(tidyr)       # Data completion and reshaping
library(gridExtra)   # Arrange multiple plots in one figure
library(grid)        # Low-level graphics (textGrob, gpar)

# load phenotype data
pheno <- read.csv("PHENO.csv", header=T)         # load age & bmi data
pheno <- pheno[, c("ID2", "Age","BMI")]
colnames(pheno) <- c("ID","Age", "BMI")          # standardize column names

# define nutrient variables
traits <- c("Calories", "Carbohydrates", "Fats", "Proteins",
            "Cholesterol", "Sodium", "Sugar", "Fiber")  

# original column names in rda files
orig.traits <- c("Calorie", "Carboidrati", "Grassi", "Proteine",
                 "Colest", "Sodio", "Zuccheri", "Fibre")    

# Define study sample (TRIESTE, CAGLIARI, BOLOGNA)
sample <- "BOLOGNA" #       !!! CHANGE HERE !!!

# define ID prefix based on sample
prefix <- switch(sample,
                 "TRIESTE"  = "X",
                 "CAGLIARI" = "S",
                 "BOLOGNA"  = "B")

# ============================================================================ #
#  LOAD AND PREPROCESS DATA
# ============================================================================ #

# Load R data file containing daily dietary diaries
load(paste0(sample, "_data.rda"))

# Ensure data is a data frame
DATA <- as.data.frame(DATA)

# Keep only total daily intake and valid collection weeks
DATA <- subset(DATA, Pasti == "Totale" & !is.na(weeks_raccolta))

# Create working dataset with English variable names
dat <- data.frame(DATA[, c("ID", "weeks_raccolta")])
colnames(dat) <- c("ID", "visit")

dat <- dat %>%
  mutate(ID = sprintf("%s%03d", prefix, ID))  # format ID with sample prefix
 
# Add nutritional variables
dat[, traits] <- DATA[, orig.traits]

# ============================================================================ #
#  COMPUTE TOTAL MEAN INTAKES
# ============================================================================ #

# Calculate total mean intake per participant across all diary days
total_means <- aggregate(dat[, traits],
                         by = list(ID = dat$ID),
                         FUN = mean,
                         na.rm = TRUE)
# Merge with phenotype data Age & BMI and add sample
total_means <- merge(total_means, pheno, by = "ID")           # add Age & BMI
total_means$sample <- sample                                  # add sample
total_means <- total_means %>%
  select(ID, sample, Age, BMI, everything())   # reorder columns

# Save total means to CSV
write.csv(total_means,
          paste0(sample, "_Diaries_TM.csv"),
          row.names = FALSE)


# ============================================================================ #
#  COMPUTE WEEKLY MEAN INTAKES
# ============================================================================ #

# Calculate mean intake per participant and collection week
weekly_means <- dat %>%
  group_by(ID, visit) %>%
  summarise(across(all_of(traits), ~ mean(.x, na.rm = TRUE)),
            .groups = "drop") %>%
  # Ensure all ID × week combinations are present
  complete(ID = unique(dat$ID),
           visit = unique(dat$visit))


# Merge with phenotype data Age & BMI and add sample
weekly_means <- merge(weekly_means, pheno, by = "ID")          # add Age & BMI
weekly_means$sample <- sample                                  # add sample
weekly_means <- weekly_means %>%
  select(ID, visit, sample, Age, BMI, everything())   # reorder columns

# Save weekly means to CSV
write.csv(weekly_means,
          paste0(sample, "_Diaries_WM.csv"),
          row.names = FALSE)


# ============================================================================ #
#  BOXPLOTS OF TOTAL MEAN INTAKES
# ============================================================================ #

# Load total mean dataset
dat <- read.csv(paste0(sample, "_Diaries_TM.csv"))

# Store participant IDs as row names
rownames(dat) <- dat$ID

# Number of participants
N.dat <- nrow(dat)

# List to store ggplot objects
plots <- list()

# Loop over each nutrient
for (trait in traits) {
  
  # Prepare data for plotting
  data <- data.frame(
    category = sample,
    value = dat[[trait]],
    label = rownames(dat)
  ) |> na.omit()
  
  # Identify extreme outliers using the 3 × IQR rule
  Q1 <- quantile(data$value, 0.25)
  Q3 <- quantile(data$value, 0.75)
  IQR_val <- IQR(data$value)
  
  lower <- Q1 - 3 * IQR_val
  upper <- Q3 + 3 * IQR_val
  
  outliers <- subset(data, value < lower | value > upper)
  
  # Create boxplot (no x-axis labels)
  bp <- ggplot(data, aes(x = category, y = value)) +
    geom_boxplot(fill = "dodgerblue1",
                 outlier.color = "dodgerblue1",
                 outlier.size = 3) +
    stat_boxplot(geom = "errorbar", width = 0.1) +
    labs(title = trait, x = NULL, y = NULL) +
    theme(
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
      axis.text.x  = element_blank(),
      axis.ticks.x = element_blank()
    )
  
  # Add extreme outliers and participant labels
  if (nrow(outliers) > 0) {
    bp <- bp +
      geom_point(data = outliers,
                 aes(x = category, y = value),
                 color = "red", size = 3) +
      geom_text_repel(data = outliers,
                      aes(label = label),
                      size = 4, color = "red")
  }
  
  plots[[trait]] <- bp
}

# Save combined boxplots as a single JPEG image
jpeg(file = paste0(sample, "_outliers.jpeg"), width = 1400, height = 800,
  units = "px", res = 100)

grid.arrange(
  grobs = plots,
  ncol = 4,
  top = textGrob(
    paste0(sample, " (N = ", N.dat, ")","\n"),
    gp = gpar(fontsize = 20, fontface = "bold")
  )
)

dev.off()


# ============================================================================ #
#  BOXPLOTS OF WEEKLY MEAN INTAKES
# ============================================================================ #

# Load the dataset of weekly means
dat <- read.csv(paste0(sample, "_Diaries_WM.csv"), header = TRUE, na.strings = "NA")

# Loop through each nutrient trait
for (trait in traits) {
  
  # Prepare data for plotting
  data <- data.frame(
    category = dat$visit,
    value = dat[[trait]],
    label = dat$ID
  )
  data <- na.omit(data)  # remove missing values
  
 # Detect extreme outliers per week
  outliers <- data %>%
    group_by(category) %>%
    mutate(
      Q1 = quantile(value, 0.25, na.rm = TRUE),
      Q3 = quantile(value, 0.75, na.rm = TRUE),
      IQR = Q3 - Q1,
      is_outlier = value < (Q1 - 3 * IQR) | value > (Q3 + 3 * IQR)
    ) %>%
    ungroup() %>%
    select(category, value, label, is_outlier) %>%
    filter(is_outlier)   # keep only TRUE
  
  # Count number of valid values per week
  n_counts <- data %>%
    mutate(category = factor(category, levels = unique(category))) %>%
    group_by(category) %>%
    summarise(N = sum(!is.na(value))) %>%
    ungroup()
  
  # Append "(N = #)" to each week label
  category_labels <- paste0(n_counts$category, " (N = ", n_counts$N, ")")
  data$category <- factor(data$category, 
                          levels = n_counts$category,
                          labels = category_labels)
  
  # Transform outliers factor to match new labels
  outliers$category <- factor(outliers$category,
                              levels = n_counts$category,
                              labels = category_labels)
  
  # Create the weekly boxplot
  bp <- ggplot(data, aes(x = category, y = value)) +
    geom_boxplot(outlier.color = "dodgerblue1",
                 fill = "dodgerblue1",
                 outlier.size = 3) +
    stat_boxplot(geom = "errorbar", width = 0.1) +
    labs(
      title = sample,
      x = "",       # no x-axis title
      y = trait
    ) +
    theme(
      axis.title = element_text(size = 15, color = "dodgerblue1", face = "bold"),
      axis.text  = element_text(size = 9, face = "bold")
    )
  
  # Add extreme outlier points and participant labels
  if (nrow(outliers) > 0) {
    bp <- bp +
      geom_point(data = outliers, aes(x = category, y = value),
                 color = "red", size = 3) +
      geom_text_repel(data = outliers, aes(label = label),
                      size = 4, color = "red")
  }
  
  # Save weekly boxplot as JPEG
  jpeg(file = paste0(sample,"_",trait, "_outliers_per_week.jpeg"),
       width = 1000, height = 500, units = "px",
       res = 120, quality = 100, bg = "white")
  print(bp)
  dev.off()
  
}
