# PAOLA FORABOSCO 28/04/2026

# ============================================================================ #
#  DESCRIPTION
# ============================================================================ #

# This script analyzes nutritional intake (Calories, Carbohydrates, Fats, 
# Proteins, Cholesterol, Sodium, Sugar, Fiber) across hormonal phases. 

# For each nutrient, it fits linear and spline mixed models, adjusting for 
# Age, BMI, and sample location, with random effects for participant ID. 
# It also compares spline vs. linear models to test if splines improve fit.

# Outputs include:
#   - Coefficient estimates and p-values for each model
#   - Global p-values for phase effects (Likelihood Ratio Test)
#   - Bonferroni-adjusted p-values
#   - Plots of estimated nutrient intake across phases

# Input: CSV file in wide format (ID, Age, BMI, sample, nutrients per phase)
# generated by the script Prepare_Diaries_3day.R

# ============================================================================ #
#  INITIALIZATION
# ============================================================================ #

# Load necessary libraries
library(splines)     # for ns() in spline models
library(lmerTest)    # lmer() with p-values
library(lme4)        # for lmer()
library(effects)     # allEffects() for plotting model effects
library(dplyr)       # data manipulation
library(gridExtra)   # arrange multiple plots in a grid
library(tidyr)   # for pivot_longer() and pivot_wider()

# Label for input/output filenames
label <- "3day_phases"                

# Read CSV data
dat <- read.csv(paste0("Diaries_", label, ".csv"), header = TRUE)
dat <- data.frame(dat)

# Identify columns containing nutrients
col.traits <- grep("_", colnames(dat), value = TRUE)

# Convert wide-format phase columns into long format for analysis
dat <- dat %>%
  pivot_longer(
    cols = all_of(col.traits),          # select phase-specific columns
    names_to = c("trait", "phase"),     # split names into trait and phase
    names_sep = "_",
    values_to = "value"                 # store values in single column
  ) %>%
  pivot_wider(names_from = trait, values_from = value) %>%  # restore nutrients as columns
  mutate(phase = as.numeric(phase))                          # convert phase to numeric

dat$ID <- as.factor(dat$ID)  # ensure ID is a factor

# Create dummy variables for sample location
dat <- dat %>%
  mutate(
    BOLOGNA  = ifelse(sample == "BOLOGNA", 1, 0),
    CAGLIARI = ifelse(sample == "CAGLIARI", 1, 0)
  )

# Traits to analyze
traits <- c("Calories", "Carbohydrates", "Fats", "Proteins", "Cholesterol",
            "Sodium", "Sugar", "Fiber")


# ============================================================================ #
#  LINEAR MODEL
# ============================================================================ #

all_pvalues <- data.frame()    # store all coefficient p-values
global_pvalues <- data.frame() # store global p-values for phase effect
plots <- list()                # store model effect plots

for (trait in traits) {
  
  # Fit linear mixed model: trait ~ phase + covariates + random ID effect
  form <- as.formula(
    paste(trait, "~ phase + Age + BMI + CAGLIARI + BOLOGNA + (1 | ID)")
  )
  model <- lmer(form, data = dat, REML = FALSE)
  
  # Fit reduced model without phase to test global effect
  form_reduced <- as.formula(
    paste(trait, "~ Age + BMI + CAGLIARI + BOLOGNA + (1 | ID)")
  )
  model_reduced <- lmer(form_reduced, data = dat, REML = FALSE)
  
  # Likelihood Ratio Test (LRT) for global phase effect
  lrt <- anova(model_reduced, model)
  
  # Store global p-value in structured data frame
  p_global <- data.frame(
    trait = trait,
    model = "linear",
    p_global = lrt$`Pr(>Chisq)`[2]
  )
  
  # Store coefficient p-values
  pvalues <- as.data.frame(coef(summary(model)))
  pvalues$trait <- trait
  pvalues$model <- "linear"
  
  # Display global p-value on plots
  text_pvalues <- ifelse(p_global$p_global > 0.05, "ns",
                         paste0("p = ", round(p_global$p_global, 4)))
  
  # Save p-values
  all_pvalues <- rbind(all_pvalues, pvalues)
  global_pvalues <- rbind(global_pvalues, p_global)
  
  # Generate effect plot with p-value as title
  plots[[trait]] <- plot(allEffects(model)[[1]], main = text_pvalues)
}

# Save plots as JPEG
jpeg(file = paste0("LINEAR_model_", label, ".jpeg"), width = 800, height = 1600,
     units = "px", res = 100)
print(grid.arrange(grobs = plots, ncol = 2))
dev.off()

# Apply Bonferroni correction to coefficient p-values
all_pvalues$p.adj.Bonf <- p.adjust(all_pvalues$`Pr(>|t|)`, method = "bonferroni")

# Export coefficient p-values to CSV
write.csv(all_pvalues, paste0("LINEAR_model_", label, "_ALL_pvalues.csv"), row.names = TRUE)

# Apply Bonferroni correction to global p-values
global_pvalues$p.adj.Bonf <- p.adjust(global_pvalues$p_global, method = "bonferroni")


# ============================================================================ #
#  SPLINE MODEL
# ============================================================================ #

all_pvalues <- data.frame()  # reset coefficient p-values
plots <- list()               # reset plots

for (trait in traits) {
  
  # Fit spline model with 3 degrees of freedom for phase
  form <- as.formula(
    paste(trait, "~ ns(phase, df = 3) + Age + BMI + CAGLIARI + BOLOGNA + (1 | ID)")
  )
  model <- lmer(form, data = dat, REML = FALSE)
  
  # Reduced model without phase for LRT
  form_reduced <- as.formula(
    paste(trait, "~ Age + BMI + CAGLIARI + BOLOGNA + (1 | ID)")
  )
  model_reduced <- lmer(form_reduced, data = dat, REML = FALSE)
  
  # LRT for global phase effect
  lrt <- anova(model_reduced, model)
  
  # Store global p-value
  p_global <- data.frame(
    trait = trait,
    model = "spline",
    p_global = lrt$`Pr(>Chisq)`[2],
    p.adj.Bonf = ""
  )
  
  # Store coefficient p-values
  pvalues <- as.data.frame(coef(summary(model)))
  pvalues$trait <- trait
  pvalues$model <- "spline"
  
  # Plot with global p-value in title
  text_pvalues <- ifelse(p_global$p_global > 0.05, "ns",
                         paste0("p = ", round(p_global$p_global, 4)))
  
  # Save p-values
  all_pvalues <- rbind(all_pvalues, pvalues)
  global_pvalues <- rbind(global_pvalues, p_global)
  
  plots[[trait]] <- plot(allEffects(model)[[1]], main = text_pvalues)
}

# Save spline plots as JPEG
jpeg(file = paste0("SPLINE_model_", label, ".jpeg"), width = 800, height = 1600,
     units = "px", res = 100)
print(grid.arrange(grobs = plots, ncol = 2))
dev.off()

# Bonferroni correction for spline coefficient p-values
all_pvalues$p.adj.Bonf <- p.adjust(all_pvalues$`Pr(>|t|)`, method = "bonferroni")

# Export spline coefficient p-values to CSV
write.csv(all_pvalues, paste0("SPLINE_model_", label, "_ALL_pvalues.csv"), row.names = TRUE)

# Bonferroni correction for spline global p-values
global_pvalues$p.adj.Bonf <- p.adjust(global_pvalues$p_global, method = "bonferroni")


# ============================================================================ #
#  SPLINE vs LINEAR MODEL COMPARISON
# ============================================================================ #

for (trait in traits) {
  
  # Fit spline model
  form <- as.formula(
    paste(trait, "~ ns(phase, df = 3) + Age + BMI + CAGLIARI + BOLOGNA + (1 | ID)")
  )
  model <- lmer(form, data = dat, REML = FALSE)
  
  # Fit linear model for comparison
  form_reduced <- as.formula(
    paste(trait, "~ phase + Age + BMI + CAGLIARI + BOLOGNA + (1 | ID)")
  )
  model_reduced <- lmer(form_reduced, data = dat, REML = FALSE)
  
  # LRT for difference between spline and linear models
  lrt <- anova(model_reduced, model)
  
  # Store p-value for spline vs linear comparison
  p_global <- data.frame(
    trait = trait,
    model = "spline_vs_linear",
    p_global = lrt$`Pr(>Chisq)`[2],
    p.adj.Bonf = ""
  )
  
  global_pvalues <- rbind(global_pvalues, p_global)
}

# Bonferroni correction for all global p-values
global_pvalues$p.adj.Bonf <- p.adjust(global_pvalues$p_global, method = "bonferroni")

# Export all global p-values (linear, spline, spline_vs_linear) to CSV
write.csv(global_pvalues, paste0("LMER_model_", label, "_pvalues.csv"), row.names = FALSE)
