# PAOLA FORABOSCO 28/04/2026

# ============================================================================ #
#  DESCRIPTION
# ============================================================================ #

# This script generates boxplots of nutritional traits across hormonal
# phases and performs paired pairwise comparisons.

# For each nutrient, the effect of Age and BMI is removed using linear regression,
# and model residuals are used for visualization and paired Wilcoxon signed-rank tests.

# Pairwise Wilcoxon p-values (nominal and Bonferroni-corrected) are exported.

# Input: CSV file in wide format (ID, Age, BMI, sample, nutrients per phase)
# generated by the script Prepare_Diaries_3day.R


# ============================================================================ #
#  INITIALIZATION
# ============================================================================ #

# Load required libraries
library(ggplot2)
library(dplyr)
library(ggsignif)
library(tidyr)

# Label for input/output filenames
label <- "3day_phases"                

# Read CSV data
dat <- read.csv(paste0("Diaries_", label, ".csv"), header = TRUE)
dat <- data.frame(dat)

# Traits to analyze
traits <- c("Calories", "Carbohydrates", "Fats", "Proteins", "Cholesterol",
            "Sodium", "Sugar", "Fiber")

# Initialize dataframe to store all p-values
all_pvalues <- data.frame()

category.name <- "phase"

# ============================================================================ #
#  BOXPLOT GENERATION & PAIRWISE TESTS
# ============================================================================ #

# Identify columns containing nutrients
col.traits <- grep("_", colnames(dat), value = TRUE)

# Convert wide-format phase columns into long format for analysis
dat <- dat %>%
  pivot_longer(
    cols = all_of(col.traits),          # select phase-specific columns
    names_to = c("trait", "phase"),     # split names into trait and phase
    names_sep = "_",
    values_to = "value"                 # store values in single column
  ) %>%
  pivot_wider(names_from = trait, values_from = value) %>%  # restore nutrients as columns
  mutate(phase = as.numeric(phase))                          # convert phase to numeric


# Loop through each trait 
 for (trait in traits) {
 #  trait <- "Calories"
   
   # --------------------- #
   # Correct for Age & BMI #
   # --------------------- #
   
   # Fit linear model using the selected trait as response and Age + BMI as predictors
   lm_model <- lm(
     as.formula(paste(trait, "~ Age + BMI")),
     data = dat,
     na.action = na.exclude
   )
   
   # Create dataframe containing category, model residuals, and ID labels

   data <- data.frame(
     category = factor(dat[[category.name]],
                       levels = c(1, 2, 3, 4)),
     value = resid(lm_model),
     label = dat$ID
   )
   
   # Count number of valid (non-NA) residual values per category
   n_counts <- data %>%
     drop_na(value) %>%           # remove rows with NA residuals
     group_by(category) %>%       # group data by category
     summarise(N = n()) %>%       # count the number of non-missing observations per category
     ungroup()
   
   # Create category labels including sample counts 
   category_labels <- paste0(n_counts$category, " (N = ", n_counts$N, ")")
   
   # Update factor levels and assign new descriptive labels
   data$category <- factor(
     data$category,
     levels = n_counts$category,   # ensure categories follow the same order as in n_counts
     labels = category_labels      # apply the category labels
   )
   
   # ------- #
   # Boxplot #
   # ------- #
   
   # Boxplot generation
   bp <- ggplot(data, aes(x = category, y = value)) +
     geom_boxplot(outlier.shape = 16, fill = "royalblue1", alpha = 0.7) +
     labs(title = "Pairwise Wilcoxon Signed-Rank Test",
          x = category.name,
          y = paste0(trait, " - corrected for Age & BMI")) +
     stat_boxplot(geom = "errorbar", width = 0.1) +
     theme_minimal() +
     theme(axis.text = element_text(size = 10, face = "bold"),
           plot.title = element_text(face = "bold", hjust = 0.5))
   
   # ----------------------------------- #
   # Pairwise Wilcoxon Test (PAIRED 2×2) #
   # ----------------------------------- #
   
   # Get all category levels from the data
   groups <- levels(data$category)
   
   # Generate all possible pairwise combinations of the categories
   comparisons <- combn(groups, 2, simplify = FALSE)
   n_comparisons <- length(comparisons)  # Number of pairwise comparisons
   
   # Function to perform paired Wilcoxon test for a single pair of groups
   paired_wilcoxon_pairwise <- function(comparison) {
     group1 <- comparison[1]
     group2 <- comparison[2]
     
     # Extract data for the two groups
     data1 <- data[data$category == group1, c("label", "value")]
     data2 <- data[data$category == group2, c("label", "value")]

     
     # Identify common subjects with non-missing values in both groups (paired data)
     common_ids <- intersect(
       data1$label[!is.na(data1$value)], 
       data2$label[!is.na(data2$value)]
     )
     
     paired_data1 <- data1$value[match(common_ids, data1$label)]
     paired_data2 <- data2$value[match(common_ids, data2$label)]
     
     # Perform paired Wilcoxon Signed-Rank test
     test_result <- wilcox.test(paired_data1, paired_data2, paired = TRUE, exact = FALSE)
     
     # Return p-value and number of paired subjects
     return(list(p_value = test_result$p.value, n_paired = length(common_ids)))
   }
   
   # Apply the paired Wilcoxon function to all pairwise comparisons
   test_results <- lapply(comparisons, paired_wilcoxon_pairwise)
   
   # Extract p-values and number of paired subjects for each comparison
   p_values <- sapply(test_results, function(x) x$p_value)
   pairwise_n <- sapply(test_results, function(x) x$n_paired)
   
   # -------------------------------- #
   # Add significance bars to boxplot #
   # -------------------------------- #
   
   # Copy the original boxplot to add significance annotations
   bpp <- bp
   
   # Calculate dynamic y positions for significance bars
   max_value <- max(data$value, na.rm = TRUE)  # Find the maximum value in the data
   y_positions <- max_value + (1:n_comparisons) * max_value/10  # Space bars above the plot
   
   # Loop over all pairwise comparisons to add significance bars
   for(i in seq_along(comparisons)) {
     bpp <- bpp + 
       geom_signif(
         comparisons = list(comparisons[[i]]),  # Specify which pair of groups to compare
         annotations = ifelse(p_values[i] < 0.001, "***",    # Add significance symbols
                              ifelse(p_values[i] < 0.01, "**",
                                     ifelse(p_values[i] < 0.05, "*", "ns"))),
         y_position = y_positions[i],  # Set vertical position of the bar
         tip_length = 0.01             # Length of the vertical tips
       )
   }
   
   # --------------------- #
   # Save the plot as JPEG #
   # --------------------- #
   jpeg(
     file = paste0(trait, "_paired_pairwise_boxplot_",label,".jpeg"),  # File name
     width = 900, height = 650, units = "px", res = 100      # Image size and resolution
   )
   print(bpp)  # Print the plot to the JPEG device
   dev.off()   # Close the device
   
   # ------------------------------ #
   # Create a results summary table #
   # ------------------------------ #
   results_table <- data.frame(
     trait,
     Group1 = sapply(comparisons, function(x) x[1]),  # First group in each comparison
     Group2 = sapply(comparisons, function(x) x[2]),  # Second group in each comparison
     Paired_N = pairwise_n,                           # Number of paired subjects
     pvalue = p_values                                # Corresponding p-values
   )
   
   # Append the current trait's results to the cumulative p-value table
   all_pvalues <- rbind(all_pvalues, results_table)
   

# End of loop for traits
 }

# ============================================================================ #
#  EXPORT ALL P-VALUES AND ADD BONFERRONI CORRECTION
# ============================================================================ #

# Add multiple testing corrections
all_pvalues$p.adj.Bonf <- p.adjust(all_pvalues$pvalue, method = "bonferroni")

# Export to CSV
write.csv(all_pvalues, paste0("pairwise_pvalues_",label,".csv"), row.names = FALSE)






