


###########################################################
###########################################################
# Script generated by: 
# Andrea Carta, email < andrea.carta88@unica.it > and Serena Sanna < serena.sanna@irgb.cnr.it >
# version date: 2023/10/09
# script related to project: "Women4Health" (PI Dr. Serena Sanna), serena.sanna@irgb.cnr.it
# for article Busonero F et al, 2023, analysis of Diet data
# tested and running on data freeze file of 20231102 (Dietary data collected until 31 August 2023)
# script tested in R version 4.2.1  and 4.3.1

###########################################################
###########################################################



library(dplyr)
library(ggplot2)
library(rstatix)
library(ggpubr)
library(tidyverse)


mydatafile="XXX.csv"
## this file contains columns with Calories and macronutriets for each meal and for each day of the dietary records, 
## as well as information on sample ID, days of menstrual cycle, day of biological sample collection, and Visit number

DF_Diari_codebook=read.csv(mydatafile)


ord <- c("first","second","third","fourth")
DF_Diari_codebook$Visit=factor(DF_Diari_codebook$Visit,levels = ord)

DF_Diari_codebook_list=split(DF_Diari_codebook,DF_Diari_codebook$ID)


#temporanely we select only the days with total calories and that are in the 4-week-cycle (max 28 days)
Diari_list_out=list()
for (i in 1:length(DF_Diari_codebook_list)) {
  
  Diari_list_out[[i]]=dplyr::filter(DF_Diari_codebook_list[[i]],! is.na(Weeks_ciclo),Pasti=="Totale")
  
}


#convert in df to save it and compute the percentiles
Diari_df_out=do.call("rbind", Diari_list_out)

Q <- quantile( Diari_df_out$Calorie, probs=c(.025, .975), na.rm = T)
#if you prefer to keep outliers, uncomment the following row
#Q=as.numeric(c(0,10000))
###########################



# now set to NA all outliers identified in Q

##for each element of list
for (i in 1:length(DF_Diari_codebook_list)) {
  
  Diari_list_out[[i]]=DF_Diari_codebook_list[[i]]
  for (j in 1:nrow(Diari_list_out[[i]])) { #put NA in this condition 
    #for breakfast lunch dinner snack
    if (Diari_list_out[[i]]$Pasti[j]=="Totale"&&
        (Diari_list_out[[i]]$Calorie[j]<Q[1]|
         Diari_list_out[[i]]$Calorie[j]>Q[2]|
         is.na(Diari_list_out[[i]]$Calorie[j]))){
      Diari_list_out[[i]]$Calorie[j]=NA
      Diari_list_out[[i]]$Grassi[j]=NA
      Diari_list_out[[i]]$Sodio[j]=NA
      Diari_list_out[[i]]$Proteine[j]=NA
      Diari_list_out[[i]]$Zuccheri[j]=NA
      Diari_list_out[[i]]$Carboidrati[j]=NA
      Diari_list_out[[i]]$Colest[j]=NA
      Diari_list_out[[i]]$Fibre[j]=NA
      
      Diari_list_out[[i]]$Calorie[j-1]=NA
      Diari_list_out[[i]]$Grassi[j-1]=NA
      Diari_list_out[[i]]$Sodio[j-1]=NA
      Diari_list_out[[i]]$Proteine[j-1]=NA
      Diari_list_out[[i]]$Zuccheri[j-1]=NA
      Diari_list_out[[i]]$Carboidrati[j-1]=NA
      Diari_list_out[[i]]$Colest[j-1]=NA
      Diari_list_out[[i]]$Fibre[j-1]=NA
      
      Diari_list_out[[i]]$Calorie[j-2]=NA
      Diari_list_out[[i]]$Grassi[j-2]=NA
      Diari_list_out[[i]]$Sodio[j-2]=NA
      Diari_list_out[[i]]$Proteine[j-2]=NA
      Diari_list_out[[i]]$Zuccheri[j-2]=NA
      Diari_list_out[[i]]$Carboidrati[j-2]=NA
      Diari_list_out[[i]]$Colest[j-2]=NA
      Diari_list_out[[i]]$Fibre[j-2]=NA
      
      Diari_list_out[[i]]$Calorie[j-3]=NA
      Diari_list_out[[i]]$Grassi[j-3]=NA
      Diari_list_out[[i]]$Sodio[j-3]=NA
      Diari_list_out[[i]]$Proteine[j-3]=NA
      Diari_list_out[[i]]$Zuccheri[j-3]=NA
      Diari_list_out[[i]]$Carboidrati[j-3]=NA
      Diari_list_out[[i]]$Colest[j-3]=NA
      Diari_list_out[[i]]$Fibre[j-3]=NA
      
      Diari_list_out[[i]]$Calorie[j-4]=NA
      Diari_list_out[[i]]$Grassi[j-4]=NA
      Diari_list_out[[i]]$Sodio[j-4]=NA
      Diari_list_out[[i]]$Proteine[j-4]=NA
      Diari_list_out[[i]]$Zuccheri[j-4]=NA
      Diari_list_out[[i]]$Carboidrati[j-4]=NA
      Diari_list_out[[i]]$Colest[j-4]=NA
      Diari_list_out[[i]]$Fibre[j-4]=NA
      
    }
  }
}
#keep the names of the volonteers
names(Diari_list_out)=names(DF_Diari_codebook_list)



#to do boxplot (BP) and other grafics we create new lists with only the 28days diet information


mega_list_BPDays=list()
for (i in 1:length(DF_Diari_codebook_list)) {
  #keep only calories and weekcicle and total 
  mega_list_BPDays[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Weeks_ciclo),Pasti=="Totale")
  mega_list_BPDays[[i]]=mega_list_BPDays[[i]]$Calorie
}
#save it as DF
mega_final_df_BPDays=t(do.call("cbind", mega_list_BPDays))
#give names to rows and cols
colnames(mega_final_df_BPDays)=as.character( seq(1,28) )
rownames(mega_final_df_BPDays)=names(DF_Diari_codebook_list)

#create vector to plot NA per days
NAperDay=colSums(is.na(mega_final_df_BPDays))

# create a plot with missing points per day
c=barplot(NAperDay,las=2,ylim = c(0,44),main="Missing points per Day",ylab="NA",xlab="Days")
w <- as.matrix(NAperDay)
text(c, w+1, labels=as.character(w))


#DF_Diari_codebook_list=Diari_list_out
#medianeGC medieGC sd per il totale




###########################################################################
#                                                                         #
#         FROM NOW ON WE COMPUTE MEDIAN ,MEAN AND SD FOR EACH WEEK/Visit  # 
#         FOR DAILY TOTAL CALORIES AND FOR MACRONUTRIENTS                 #
#
#         Then, Compute  Wilcox and Friedman Test  and create plots       #
#######################################################################


# First, we need for factorize the weeks
ord <- c("first","second","third","fourth")


###############################################
####    -> Calories <-    ###########
#median mean and SD for total                 
#keep only those who are in weeks Visit
mega_list_GRCal=list()
for (i in 1:length(Diari_list_out)) {
  
  mega_list_GRCal[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Visit),Pasti=="Totale")
  
}



#Compute Median mean and SD
medianeGR_Cal=list()
medieGR_Cal=list()
st_devGR_Cal=list()
for (i in 1:length(mega_list_GRCal)) {
  medianeGR_Cal[[i]]=tapply( mega_list_GRCal[[i]]$Calorie, mega_list_GRCal[[i]]$Visit, median, na.rm = TRUE) 
  medianeGR_Cal[[i]]=as.data.frame(t(medianeGR_Cal[[i]]))
  
  medieGR_Cal[[i]]=tapply( mega_list_GRCal[[i]]$Calorie, mega_list_GRCal[[i]]$Visit, mean, na.rm = TRUE) 
  medieGR_Cal[[i]]=as.data.frame(t(medieGR_Cal[[i]]))
  
  st_devGR_Cal[[i]]=tapply( mega_list_GRCal[[i]]$Calorie, mega_list_GRCal[[i]]$Visit, sd, na.rm = TRUE) 
  st_devGR_Cal[[i]]=as.data.frame(t(st_devGR_Cal[[i]]))
}


#Save as DF
medianeGR_Cal_df=do.call("rbind", medianeGR_Cal)
medieGR_Cal_df=do.call("rbind", medieGR_Cal)
st_devGR_Cal_df=do.call("rbind", st_devGR_Cal)

#Test and Plot


#box plot medians (can use mean if interesed just change medianeGR_Cal_df --> medieGR_Cal_df)

#this is use to create the format that wilcox_test requires
medianeGR_Cal_dotplot <- medianeGR_Cal_df %>%
  tidyr::pivot_longer(cols = everything(), names_to = "variable") %>%
  arrange(variable) %>%
  mutate(value = rep(value, each = 1))
colnames(medianeGR_Cal_dotplot)=c("Visit","Cal")
ID_diari=rep(names(Diari_list_out),4)
#put also ID volonteers
medianeGR_Cal_dotplot=data.frame(medianeGR_Cal_dotplot,ID=factor(ID_diari))
#save as factor
medianeGR_Cal_dotplot$Visit=factor(medianeGR_Cal_dotplot$Visit,levels = ord)

#Friedman test 
FT_medianeGR_Cal=friedman.test(medianeGR_Cal_dotplot$Cal,
                               groups = medianeGR_Cal_dotplot$Visit,
                               blocks = medianeGR_Cal_dotplot$ID,
                               data=medianeGR_Cal_dotplot)
#save it as text
text_FT_medianeGR_Cal=(paste("Friedman Test","p =",round(FT_medianeGR_Cal$p.value,4)))

#Apply Wilcox test paired corrected by bonferroni
WT_medianeGR_Cal=medianeGR_Cal_dotplot %>%
  wilcox_test(Cal ~ Visit,
              paired=TRUE, p.adjust.method = "bonferroni" )
WT_medianeGR_Cal$p.adj=round(WT_medianeGR_Cal$p.adj,6)
WT_medianeGR_Cal <- WT_medianeGR_Cal %>% add_xy_position(x = "Visit",step.increase = 0.60)
#Plot results and test
ggboxplot(medianeGR_Cal_dotplot, x = "Visit", y = "Cal",
          color = "Visit", palette = "jco",add = "jitter")+
  labs(title="Median Total Calories per Visit",x="Weeks", y = "Calories",subtitle = text_FT_medianeGR_Cal)+
  stat_pvalue_manual(WT_medianeGR_Cal,label="p.adj",tip.length = 0.03)


###  -> Carbohydrates <- ###
#median mean and SD for total                 
#keep only those who are in Visit Week
mega_list_GRcarbs=list()
for (i in 1:length(Diari_list_out)) {
  
  mega_list_GRcarbs[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Visit),Pasti=="Totale")
  
}



#Compute Median mean and SD
medianeGR_carbs=list()
medieGR_carbs=list()
st_devGR_carbs=list()
for (i in 1:length(mega_list_GRcarbs)) {
  medianeGR_carbs[[i]]=tapply( mega_list_GRcarbs[[i]]$Carboidrati, mega_list_GRcarbs[[i]]$Visit, median, na.rm = TRUE) 
  medianeGR_carbs[[i]]=as.data.frame(t(medianeGR_carbs[[i]]))
  
  medieGR_carbs[[i]]=tapply( mega_list_GRcarbs[[i]]$Carboidrati, mega_list_GRcarbs[[i]]$Visit, mean, na.rm = TRUE) 
  medieGR_carbs[[i]]=as.data.frame(t(medieGR_carbs[[i]]))
  
  st_devGR_carbs[[i]]=tapply( mega_list_GRcarbs[[i]]$Carboidrati, mega_list_GRcarbs[[i]]$Visit, sd, na.rm = TRUE) 
  st_devGR_carbs[[i]]=as.data.frame(t(st_devGR_carbs[[i]]))
}


#Save as DF
medianeGR_carbs_df=do.call("rbind", medianeGR_carbs)
medieGR_carbs_df=do.call("rbind", medieGR_carbs)
st_devGR_carbs_df=do.call("rbind", st_devGR_carbs)

#Test and Plot


#box plot medians (can use mean if interesed just change medianeGR_carbs_df --> medieGR_carbs_df)

#this is use to create the format that wilcox_test requires
medianeGR_carbs_dotplot <- medianeGR_carbs_df %>%
  tidyr::pivot_longer(cols = everything(), names_to = "variable") %>%
  arrange(variable) %>%
  mutate(value = rep(value, each = 1))
colnames(medianeGR_carbs_dotplot)=c("Visit","carbs")
ID_diari=rep(names(Diari_list_out),4)
#put also ID volonteers
medianeGR_carbs_dotplot=data.frame(medianeGR_carbs_dotplot,ID=factor(ID_diari))
#save as factor
medianeGR_carbs_dotplot$Visit=factor(medianeGR_carbs_dotplot$Visit,levels = ord)

#Friedman test 
FT_medianeGR_carbs=friedman.test(medianeGR_carbs_dotplot$carbs,
                                 groups = medianeGR_carbs_dotplot$Visit,
                                 blocks = medianeGR_carbs_dotplot$ID,
                                 data=medianeGR_carbs_dotplot)
#save it as text
text_FT_medianeGR_carbs=(paste("Friedman Test","p =",round(FT_medianeGR_carbs$p.value,4)))

#Apply Wilcox test paired corrected by bonferroni
WT_medianeGR_carbs=medianeGR_carbs_dotplot %>%
  wilcox_test(carbs ~ Visit,
              paired=TRUE, p.adjust.method = "bonferroni" )
WT_medianeGR_carbs$p.adj=round(WT_medianeGR_carbs$p.adj,6)
WT_medianeGR_carbs <- WT_medianeGR_carbs %>% add_xy_position(x = "Visit",step.increase = 0.60)
#Plot results and test
ggboxplot(medianeGR_carbs_dotplot, x = "Visit", y = "carbs",
          color = "Visit", palette = "jco",add = "jitter")+
  labs(title="Median Total Carbohydrates per Visit",x="Weeks", y = "Carbohydrates",subtitle = text_FT_medianeGR_carbs)+
  stat_pvalue_manual(WT_medianeGR_carbs,label="p.adj",tip.length = 0.03)


##############################################
###############################################
######    ->   Proteins <-   #####
#median mean and SD for total                
#keep only those who are in Visit Week
mega_list_GRprot=list()
for (i in 1:length(Diari_list_out)) {
  
  mega_list_GRprot[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Visit),Pasti=="Totale")
  
}



#Compute Median mean and SD
medianeGR_prot=list()
medieGR_prot=list()
st_devGR_prot=list()
for (i in 1:length(mega_list_GRprot)) {
  medianeGR_prot[[i]]=tapply( mega_list_GRprot[[i]]$Proteine, mega_list_GRprot[[i]]$Visit, median, na.rm = TRUE) 
  medianeGR_prot[[i]]=as.data.frame(t(medianeGR_prot[[i]]))
  
  medieGR_prot[[i]]=tapply( mega_list_GRprot[[i]]$Proteine, mega_list_GRprot[[i]]$Visit, mean, na.rm = TRUE) 
  medieGR_prot[[i]]=as.data.frame(t(medieGR_prot[[i]]))
  
  st_devGR_prot[[i]]=tapply( mega_list_GRprot[[i]]$Proteine, mega_list_GRprot[[i]]$Visit, sd, na.rm = TRUE) 
  st_devGR_prot[[i]]=as.data.frame(t(st_devGR_prot[[i]]))
}


#Save as DF
medianeGR_prot_df=do.call("rbind", medianeGR_prot)
medieGR_prot_df=do.call("rbind", medieGR_prot)
st_devGR_prot_df=do.call("rbind", st_devGR_prot)

#Test and Plot


#box plot medians (can use mean if interesed just change medianeGR_prot_df --> medieGR_prot_df)

#this is use to create the format that wilcox_test requires
medianeGR_prot_dotplot <- medianeGR_prot_df %>%
  tidyr::pivot_longer(cols = everything(), names_to = "variable") %>%
  arrange(variable) %>%
  mutate(value = rep(value, each = 1))
colnames(medianeGR_prot_dotplot)=c("Visit","prot")
ID_diari=rep(names(Diari_list_out),4)
#put also ID volonteers
medianeGR_prot_dotplot=data.frame(medianeGR_prot_dotplot,ID=factor(ID_diari))
#save as factor
medianeGR_prot_dotplot$Visit=factor(medianeGR_prot_dotplot$Visit,levels = ord)

#Friedman test 
FT_medianeGR_prot=friedman.test(medianeGR_prot_dotplot$prot,
                                groups = medianeGR_prot_dotplot$Visit,
                                blocks = medianeGR_prot_dotplot$ID,
                                data=medianeGR_prot_dotplot)
#save it as text
text_FT_medianeGR_prot=(paste("Friedman Test","p =",round(FT_medianeGR_prot$p.value,4)))

#Apply Wilcox test paired corrected by bonferroni
WT_medianeGR_prot=medianeGR_prot_dotplot %>%
  wilcox_test(prot ~ Visit,
              paired=TRUE, p.adjust.method = "bonferroni" )
WT_medianeGR_prot$p.adj=round(WT_medianeGR_prot$p.adj,6)
WT_medianeGR_prot <- WT_medianeGR_prot %>% add_xy_position(x = "Visit",step.increase = 0.60)
#Plot results and test
ggboxplot(medianeGR_prot_dotplot, x = "Visit", y = "prot",
          color = "Visit", palette = "jco",add = "jitter")+
  labs(title="Median Total Proteins per Visit",x="Weeks", y = "Proteins",subtitle = text_FT_medianeGR_prot)+
  stat_pvalue_manual(WT_medianeGR_prot,label="p.adj",tip.length = 0.03)



##############################################
###############################################
######   ->  Fibers <-   ############
#median mean and SD for total                 
#keep only those who are in Visit Week
mega_list_GRfibr=list()
for (i in 1:length(Diari_list_out)) {
  
  mega_list_GRfibr[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Visit),Pasti=="Totale")
  
}



#Compute Median mean and SD
medianeGR_fibr=list()
medieGR_fibr=list()
st_devGR_fibr=list()
for (i in 1:length(mega_list_GRfibr)) {
  medianeGR_fibr[[i]]=tapply( mega_list_GRfibr[[i]]$Fibre, mega_list_GRfibr[[i]]$Visit, median, na.rm = TRUE) 
  medianeGR_fibr[[i]]=as.data.frame(t(medianeGR_fibr[[i]]))
  
  medieGR_fibr[[i]]=tapply( mega_list_GRfibr[[i]]$Fibre, mega_list_GRfibr[[i]]$Visit, mean, na.rm = TRUE) 
  medieGR_fibr[[i]]=as.data.frame(t(medieGR_fibr[[i]]))
  
  st_devGR_fibr[[i]]=tapply( mega_list_GRfibr[[i]]$Fibre, mega_list_GRfibr[[i]]$Visit, sd, na.rm = TRUE) 
  st_devGR_fibr[[i]]=as.data.frame(t(st_devGR_fibr[[i]]))
}


#Save as DF
medianeGR_fibr_df=do.call("rbind", medianeGR_fibr)
medieGR_fibr_df=do.call("rbind", medieGR_fibr)
st_devGR_fibr_df=do.call("rbind", st_devGR_fibr)

#Test and Plot


#box plot medians (can use mean if interesed just change medianeGR_fibr_df --> medieGR_fibr_df)

#this is use to create the format that wilcox_test requires
medianeGR_fibr_dotplot <- medianeGR_fibr_df %>%
  tidyr::pivot_longer(cols = everything(), names_to = "variable") %>%
  arrange(variable) %>%
  mutate(value = rep(value, each = 1))
colnames(medianeGR_fibr_dotplot)=c("Visit","fibr")
ID_diari=rep(names(Diari_list_out),4)
#put also ID volonteers
medianeGR_fibr_dotplot=data.frame(medianeGR_fibr_dotplot,ID=factor(ID_diari))
#save as factor
medianeGR_fibr_dotplot$Visit=factor(medianeGR_fibr_dotplot$Visit,levels = ord)

#Friedman test 
FT_medianeGR_fibr=friedman.test(medianeGR_fibr_dotplot$fibr,
                                groups = medianeGR_fibr_dotplot$Visit,
                                blocks = medianeGR_fibr_dotplot$ID,
                                data=medianeGR_fibr_dotplot)
#save it as text
text_FT_medianeGR_fibr=(paste("Friedman Test","p =",round(FT_medianeGR_fibr$p.value,4)))

#Apply Wilcox test paired corrected by bonferroni
WT_medianeGR_fibr=medianeGR_fibr_dotplot %>%
  wilcox_test(fibr ~ Visit,
              paired=TRUE, p.adjust.method = "bonferroni" )
WT_medianeGR_fibr$p.adj=round(WT_medianeGR_fibr$p.adj,6)
WT_medianeGR_fibr <- WT_medianeGR_fibr %>% add_xy_position(x = "Visit",step.increase = 0.60)
#Plot results and test
ggboxplot(medianeGR_fibr_dotplot, x = "Visit", y = "fibr",
          color = "Visit", palette = "jco",add = "jitter")+
  labs(title="Median Total Fibers per Visit",x="Weeks", y = "Fibers",subtitle = text_FT_medianeGR_fibr)+
  stat_pvalue_manual(WT_medianeGR_fibr,label="p.adj",tip.length = 0.03)


##############################################
###############################################
#######  ->  Cholesterol <- ###########
#median mean and SD for total                 
#keep only those who are in Visit Week
mega_list_GRcolest=list()
for (i in 1:length(Diari_list_out)) {
  
  mega_list_GRcolest[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Visit),Pasti=="Totale")
  
}



#Compute Median mean and SD
medianeGR_colest=list()
medieGR_colest=list()
st_devGR_colest=list()
for (i in 1:length(mega_list_GRcolest)) {
  medianeGR_colest[[i]]=tapply( mega_list_GRcolest[[i]]$Colest, mega_list_GRcolest[[i]]$Visit, median, na.rm = TRUE) 
  medianeGR_colest[[i]]=as.data.frame(t(medianeGR_colest[[i]]))
  
  medieGR_colest[[i]]=tapply( mega_list_GRcolest[[i]]$Colest, mega_list_GRcolest[[i]]$Visit, mean, na.rm = TRUE) 
  medieGR_colest[[i]]=as.data.frame(t(medieGR_colest[[i]]))
  
  st_devGR_colest[[i]]=tapply( mega_list_GRcolest[[i]]$Colest, mega_list_GRcolest[[i]]$Visit, sd, na.rm = TRUE) 
  st_devGR_colest[[i]]=as.data.frame(t(st_devGR_colest[[i]]))
}


#Save as DF
medianeGR_colest_df=do.call("rbind", medianeGR_colest)
medieGR_colest_df=do.call("rbind", medieGR_colest)
st_devGR_colest_df=do.call("rbind", st_devGR_colest)

#Test and Plot


#box plot medians (can use mean if interesed just change medianeGR_colest_df --> medieGR_colest_df)

#this is use to create the format that wilcox_test requires
medianeGR_colest_dotplot <- medianeGR_colest_df %>%
  tidyr::pivot_longer(cols = everything(), names_to = "variable") %>%
  arrange(variable) %>%
  mutate(value = rep(value, each = 1))
colnames(medianeGR_colest_dotplot)=c("Visit","colest")
ID_diari=rep(names(Diari_list_out),4)
#put also ID volonteers
medianeGR_colest_dotplot=data.frame(medianeGR_colest_dotplot,ID=factor(ID_diari))
#save as factor
medianeGR_colest_dotplot$Visit=factor(medianeGR_colest_dotplot$Visit,levels = ord)

#Friedman test 
FT_medianeGR_colest=friedman.test(medianeGR_colest_dotplot$colest,
                                  groups = medianeGR_colest_dotplot$Visit,
                                  blocks = medianeGR_colest_dotplot$ID,
                                  data=medianeGR_colest_dotplot)
#save it as text
text_FT_medianeGR_colest=(paste("Friedman Test","p =",round(FT_medianeGR_colest$p.value,4)))

#Apply Wilcox test paired corrected by bonferroni
WT_medianeGR_colest=medianeGR_colest_dotplot %>%
  wilcox_test(colest ~ Visit,
              paired=TRUE, p.adjust.method = "bonferroni" )
WT_medianeGR_colest$p.adj=round(WT_medianeGR_colest$p.adj,6)
WT_medianeGR_colest <- WT_medianeGR_colest %>% add_xy_position(x = "Visit",step.increase = 0.60)
#Plot results and test
ggboxplot(medianeGR_colest_dotplot, x = "Visit", y = "colest",
          color = "Visit", palette = "jco",add = "jitter")+
  labs(title="Median Total Cholesterol per Visit",x="Weeks", y = "Cholesterol",subtitle = text_FT_medianeGR_colest)+
  stat_pvalue_manual(WT_medianeGR_colest,label="p.adj",tip.length = 0.03)

##############


##############################################
###############################################
#########  -> Fats <-  ###############
#median mean and SD for total                  
#keep only those who are in Visit Week
mega_list_GRFat=list()
for (i in 1:length(Diari_list_out)) {
  
  mega_list_GRFat[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Visit),Pasti=="Totale")
  
}



#Compute Median mean and SD
medianeGR_Fat=list()
medieGR_Fat=list()
st_devGR_Fat=list()
for (i in 1:length(mega_list_GRFat)) {
  medianeGR_Fat[[i]]=tapply( as.numeric(mega_list_GRFat[[i]]$Grassi), mega_list_GRFat[[i]]$Visit, median, na.rm = TRUE) 
  medianeGR_Fat[[i]]=as.data.frame(t(medianeGR_Fat[[i]]))
  
  medieGR_Fat[[i]]=tapply( as.numeric(mega_list_GRFat[[i]]$Grassi), mega_list_GRFat[[i]]$Visit, mean, na.rm = TRUE) 
  medieGR_Fat[[i]]=as.data.frame(t(medieGR_Fat[[i]]))
  
  st_devGR_Fat[[i]]=tapply( as.numeric(mega_list_GRFat[[i]]$Grassi), mega_list_GRFat[[i]]$Visit, sd, na.rm = TRUE) 
  st_devGR_Fat[[i]]=as.data.frame(t(st_devGR_Fat[[i]]))
}


#Save as DF
medianeGR_Fat_df=do.call("rbind", medianeGR_Fat)
medieGR_Fat_df=do.call("rbind", medieGR_Fat)
st_devGR_Fat_df=do.call("rbind", st_devGR_Fat)

#Test and Plot


#box plot medians (can use mean if interesed just change medianeGR_Fat_df --> medieGR_Fat_df)

#this is use to create the format that wilcox_test requires
medianeGR_Fat_dotplot <- medianeGR_Fat_df %>%
  tidyr::pivot_longer(cols = everything(), names_to = "variable") %>%
  arrange(variable) %>%
  mutate(value = rep(value, each = 1))
colnames(medianeGR_Fat_dotplot)=c("Visit","Fat")
ID_diari=rep(names(Diari_list_out),4)
#put also ID volonteers
medianeGR_Fat_dotplot=data.frame(medianeGR_Fat_dotplot,ID=factor(ID_diari))
#save as factor
medianeGR_Fat_dotplot$Visit=factor(medianeGR_Fat_dotplot$Visit,levels = ord)

#Friedman test 
FT_medianeGR_Fat=friedman.test(medianeGR_Fat_dotplot$Fat,
                               groups = medianeGR_Fat_dotplot$Visit,
                               blocks = medianeGR_Fat_dotplot$ID,
                               data=medianeGR_Fat_dotplot)
#save it as text
text_FT_medianeGR_Fat=(paste("Friedman Test","p =",round(FT_medianeGR_Fat$p.value,4)))

#Apply Wilcox test paired corrected by bonferroni
WT_medianeGR_Fat=medianeGR_Fat_dotplot %>%
  wilcox_test(Fat ~ Visit,
              paired=TRUE, p.adjust.method = "bonferroni" )
WT_medianeGR_Fat$p.adj=round(WT_medianeGR_Fat$p.adj,6)
WT_medianeGR_Fat <- WT_medianeGR_Fat %>% add_xy_position(x = "Visit",step.increase = 0.60)
#Plot results and test
ggboxplot(medianeGR_Fat_dotplot, x = "Visit", y = "Fat",
          color = "Visit", palette = "jco",add = "jitter")+
  labs(title="Median Total Fats per Visit",x="Weeks", y = "Fats",subtitle = text_FT_medianeGR_Fat)+
  stat_pvalue_manual(WT_medianeGR_Fat,label="p.adj",tip.length = 0.03)




##############################################
###############################################
#######    -> Sugar <-  #############
#median mean and SD for total                  
#keep only those who are in Visit Week
mega_list_GRzucch=list()
for (i in 1:length(Diari_list_out)) {
  
  mega_list_GRzucch[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Visit),Pasti=="Totale")
  
}



#Compute Median mean and SD
medianeGR_zucch=list()
medieGR_zucch=list()
st_devGR_zucch=list()
for (i in 1:length(mega_list_GRzucch)) {
  medianeGR_zucch[[i]]=tapply( mega_list_GRzucch[[i]]$Zuccheri, mega_list_GRzucch[[i]]$Visit, median, na.rm = TRUE) 
  medianeGR_zucch[[i]]=as.data.frame(t(medianeGR_zucch[[i]]))
  
  medieGR_zucch[[i]]=tapply( mega_list_GRzucch[[i]]$Zuccheri, mega_list_GRzucch[[i]]$Visit, mean, na.rm = TRUE) 
  medieGR_zucch[[i]]=as.data.frame(t(medieGR_zucch[[i]]))
  
  st_devGR_zucch[[i]]=tapply( mega_list_GRzucch[[i]]$Zuccheri, mega_list_GRzucch[[i]]$Visit, sd, na.rm = TRUE) 
  st_devGR_zucch[[i]]=as.data.frame(t(st_devGR_zucch[[i]]))
}


#Save as DF
medianeGR_zucch_df=do.call("rbind", medianeGR_zucch)
medieGR_zucch_df=do.call("rbind", medieGR_zucch)
st_devGR_zucch_df=do.call("rbind", st_devGR_zucch)

#Test and Plot


#box plot medians (can use mean if interesed just change medianeGR_zucch_df --> medieGR_zucch_df)

#this is use to create the format that wilcox_test requires
medianeGR_zucch_dotplot <- medianeGR_zucch_df %>%
  tidyr::pivot_longer(cols = everything(), names_to = "variable") %>%
  arrange(variable) %>%
  mutate(value = rep(value, each = 1))
colnames(medianeGR_zucch_dotplot)=c("Visit","zucch")
ID_diari=rep(names(Diari_list_out),4)
#put also ID volonteers
medianeGR_zucch_dotplot=data.frame(medianeGR_zucch_dotplot,ID=factor(ID_diari))
#save as factor
medianeGR_zucch_dotplot$Visit=factor(medianeGR_zucch_dotplot$Visit,levels = ord)

#Friedman test 
FT_medianeGR_zucch=friedman.test(medianeGR_zucch_dotplot$zucch,
                                 groups = medianeGR_zucch_dotplot$Visit,
                                 blocks = medianeGR_zucch_dotplot$ID,
                                 data=medianeGR_zucch_dotplot)
#save it as text
text_FT_medianeGR_zucch=(paste("Friedman Test","p =",round(FT_medianeGR_zucch$p.value,4)))

#Apply Wilcox test paired corrected by bonferroni
WT_medianeGR_zucch=medianeGR_zucch_dotplot %>%
  wilcox_test(zucch ~ Visit,
              paired=TRUE, p.adjust.method = "bonferroni" )
WT_medianeGR_zucch$p.adj=round(WT_medianeGR_zucch$p.adj,6)
WT_medianeGR_zucch <- WT_medianeGR_zucch %>% add_xy_position(x = "Visit",step.increase = 0.60)
#Plot results and test
ggboxplot(medianeGR_zucch_dotplot, x = "Visit", y = "zucch",
          color = "Visit", palette = "jco",add = "jitter")+
  labs(title="Median Total Sugar per Visit",x="Weeks", y = "Sugar",subtitle = text_FT_medianeGR_zucch)+
  stat_pvalue_manual(WT_medianeGR_zucch,label="p.adj",tip.length = 0.03)




##############################################
###############################################
#########     -> Sodium <- ##############
#median mean and SD for total                
#keep only those who are in Visit Week
mega_list_GRSod=list()
for (i in 1:length(Diari_list_out)) {
  
  mega_list_GRSod[[i]]=dplyr::filter(Diari_list_out[[i]],! is.na(Visit),Pasti=="Totale")
  
}



#Compute Median mean and SD
medianeGR_Sod=list()
medieGR_Sod=list()
st_devGR_Sod=list()
for (i in 1:length(mega_list_GRSod)) {
  medianeGR_Sod[[i]]=tapply( mega_list_GRSod[[i]]$Sodio, mega_list_GRSod[[i]]$Visit, median, na.rm = TRUE) 
  medianeGR_Sod[[i]]=as.data.frame(t(medianeGR_Sod[[i]]))
  
  medieGR_Sod[[i]]=tapply( mega_list_GRSod[[i]]$Sodio, mega_list_GRSod[[i]]$Visit, mean, na.rm = TRUE) 
  medieGR_Sod[[i]]=as.data.frame(t(medieGR_Sod[[i]]))
  
  st_devGR_Sod[[i]]=tapply( mega_list_GRSod[[i]]$Sodio, mega_list_GRSod[[i]]$Visit, sd, na.rm = TRUE) 
  st_devGR_Sod[[i]]=as.data.frame(t(st_devGR_Sod[[i]]))
}


#Save as DF
medianeGR_Sod_df=do.call("rbind", medianeGR_Sod)
medieGR_Sod_df=do.call("rbind", medieGR_Sod)
st_devGR_Sod_df=do.call("rbind", st_devGR_Sod)

#Test and Plot


#box plot medians (can use mean if interesed just change medianeGR_Sod_df --> medieGR_Sod_df)

#this is use to create the format that wilcox_test requires
medianeGR_Sod_dotplot <- medianeGR_Sod_df %>%
  tidyr::pivot_longer(cols = everything(), names_to = "variable") %>%
  arrange(variable) %>%
  mutate(value = rep(value, each = 1))
colnames(medianeGR_Sod_dotplot)=c("Visit","Sod")
ID_diari=rep(names(Diari_list_out),4)
#put also ID volonteers
medianeGR_Sod_dotplot=data.frame(medianeGR_Sod_dotplot,ID=factor(ID_diari))
#save as factor
medianeGR_Sod_dotplot$Visit=factor(medianeGR_Sod_dotplot$Visit,levels = ord)

#Friedman test 
FT_medianeGR_Sod=friedman.test(medianeGR_Sod_dotplot$Sod,
                               groups = medianeGR_Sod_dotplot$Visit,
                               blocks = medianeGR_Sod_dotplot$ID,
                               data=medianeGR_Sod_dotplot)
#save it as text
text_FT_medianeGR_Sod=(paste("Friedman Test","p =",round(FT_medianeGR_Sod$p.value,4)))

#Apply Wilcox test paired corrected by bonferroni
WT_medianeGR_Sod=medianeGR_Sod_dotplot %>%
  wilcox_test(Sod ~ Visit,
              paired=TRUE, p.adjust.method = "bonferroni" )
WT_medianeGR_Sod$p.adj=round(WT_medianeGR_Sod$p.adj,6)
WT_medianeGR_Sod <- WT_medianeGR_Sod %>% add_xy_position(x = "Visit",step.increase = 0.60)
#Plot results and test
ggboxplot(medianeGR_Sod_dotplot, x = "Visit", y = "Sod",
          color = "Visit", palette = "jco",add = "jitter")+
  labs(title="Median Total Sodium per Visit",x="Weeks", y = "Sodium",subtitle = text_FT_medianeGR_Sod)+
  stat_pvalue_manual(WT_medianeGR_Sod,label="p.adj",tip.length = 0.03)



##########################################################
# now merge all results and write a file with results
###########################################################


res_TOT_FT=rbind(c("Calories",text_FT_medianeGR_Cal),
              c("Chol",text_FT_medianeGR_colest),
              c("Sugar",text_FT_medianeGR_zucch),
              c("Carbs",text_FT_medianeGR_carbs),
              c("Prot",text_FT_medianeGR_prot),
              c("Fat",text_FT_medianeGR_Fat),
              c("Sodium",text_FT_medianeGR_Sod),
              c("Fibers",text_FT_medianeGR_fibr))

colnames(res_TOT_FT)=c("variable","pvalue")

print(res_TOT_FT)


res_TOT_WT=rbind(
            data.frame(WT_medianeGR_Cal)[,1:9],
            data.frame(WT_medianeGR_colest)[,1:9],
            data.frame(WT_medianeGR_carbs)[,1:9],
            data.frame(WT_medianeGR_prot)[,1:9],
            data.frame(WT_medianeGR_Fat)[,1:9],
            data.frame(WT_medianeGR_Sod)[,1:9],
            data.frame(WT_medianeGR_fibr)[,1:9])


colnames(res_TOT_WT)=c("variable","Tp1","Tp2","n1","n2","statistics", "p","p.adj","Signif")

##write results to a csv file
write.csv(res_TOT_FT,file="results_FT_dietvariables.csv",quote=FALSE, na="NA",row.names=FALSE)

write.csv(res_TOT_WT,file="results_WT_dietvariables.csv",quote=FALSE, na="NA",row.names=FALSE)


