


###########################################################
###########################################################
# Script generated by: 
# Andrea Carta, email < acarta88@unica.it > and Serena Sanna < serena.sanna@irgb.cnr.it >
# version date: 2023/10/09
# script related to project: "Women4Health" (PI Dr. Serena Sanna), serena.sanna@irgb.cnr.it
# for article Busonero F et al, 2023; analysis of clinical phenotypes 
# tested and running on data freeze 20231009 (Data collected until 31 August 2023)
# script tested in R version 4.2.1  and 4.3.1

###########################################################
###########################################################


library(rstatix)
library(ggpubr)
library(psych)
library(xtable)


# mydatafile -> csv file containing information on volunteers. Volunteers are listed in rows and repeated as many times they have been collected
# expected columts are sampleID, Visit, Week, date of collection, phenotype1, phenotype2, ... 



mydatafile="XXX.csv"
DF_blood_horm_food=read.csv(mydatafile)


## convert italian names to English
colnames(DF_blood_horm_food)[which(colnames(DF_blood_horm_food)=="settimane")]<-"Weeks"
colnames(DF_blood_horm_food)[which(colnames(DF_blood_horm_food)=="Visita")]<-"Visit"


#####Compute HOMA_IR and HOMA_IB 

HOMA_IR=rep(NA,nrow(DF_blood_horm_food))
HOMA_B=rep(NA,nrow(DF_blood_horm_food))

DF_blood_horm_food=data.frame(DF_blood_horm_food[,-which(colnames(DF_blood_horm_food)=="dataraccolta")],HOMA_IR,HOMA_B,dataraccolta=DF_blood_horm_food[,which(colnames(DF_blood_horm_food)=="dataraccolta")])
DF_blood_horm_food$INS=as.numeric(DF_blood_horm_food$INS)
DF_blood_horm_food$GL=as.numeric(DF_blood_horm_food$GL)

for(i in 1:nrow(DF_blood_horm_food)){
  if(!is.na(DF_blood_horm_food$GL[i]) & !is.na(DF_blood_horm_food$INS[i]) ){
    
    DF_blood_horm_food$HOMA_IR[i]=((DF_blood_horm_food$INS[i])*DF_blood_horm_food$GL[i])/405
    DF_blood_horm_food$HOMA_B[i]=(20*DF_blood_horm_food$INS[i])/(DF_blood_horm_food$GL[i]-63)
    
  }
  
}



###########################################################
# start analysis for HOMA_IR
###########################################################



# create HOMA_IR data set



data_HOMA_IR=data.frame(DF_blood_horm_food$Visit,DF_blood_horm_food$HOMA_IR,DF_blood_horm_food$ID)

## WARNING: Andrea version did not work ; the column Visit is converted into numeric values and later cannot be sorted
## Andrea version is: data_HOMA_B=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$HOMA_B,DF_blood_horm_food$ID))


colnames(data_HOMA_IR)=c("Visit","HOMA_IR","ID")
ord <- c("first","second","third","fourth")
data_HOMA_IR$Visit=factor(data_HOMA_IR$Visit,levels = ord)
data_HOMA_IR$HOMA_IR=as.numeric(data_HOMA_IR$HOMA_IR)



## Calculate Friedmant test 
FT_HOMA_IR=friedman.test(data_HOMA_IR$HOMA_IR,groups = data_HOMA_IR$Visit,
                         blocks = data_HOMA_IR$ID,data=data_HOMA_IR)
text_FT_HOMA_IR=(paste("Friedman Test","p =",round(FT_HOMA_IR$p.value,4)))



## Calculate wilcoxon-test for paired data(adjust using bonferroni) and generate plot

WT_HOMA_IR=data_HOMA_IR %>%
  wilcox_test(HOMA_IR ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_HOMA_IR$p.adj=round(WT_HOMA_IR$p.adj,6)
WT_HOMA_IR <- WT_HOMA_IR %>% add_xy_position(x = "Visit",step.increase = 0.60)
ggboxplot(data_HOMA_IR, x = "Visit", y = "HOMA_IR",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="HOMA-IR",x="Weeks", y = "HOMA-IR",subtitle = text_FT_HOMA_IR )+
  stat_pvalue_manual(WT_HOMA_IR,label="p.adj",tip.length = 0.01)




## save in a table the difference between means and significance , for each pair comparison

res_HOMA_IR=matrix(NA,nrow=nrow(WT_HOMA_IR),ncol=9)
for(i in 1:nrow(WT_HOMA_IR)){
  
  testdata_HOMA_IR=cbind(data_HOMA_IR[data_HOMA_IR$Visit==WT_HOMA_IR$group1[i],"HOMA_IR"],data_HOMA_IR[data_HOMA_IR$Visit==WT_HOMA_IR$group2[i],"HOMA_IR"])
  testdata_HOMA_IR=na.omit(testdata_HOMA_IR)
  res_HOMA_IR[i,]=print(c(WT_HOMA_IR$.y.[i],WT_HOMA_IR$group1[i],WT_HOMA_IR$group2[i],WT_HOMA_IR$n1[i],
                          WT_HOMA_IR$n2[i],"diff between means",
                          round(mean(testdata_HOMA_IR[,1]-testdata_HOMA_IR[,2]),4),
                          WT_HOMA_IR$p.adj[i],WT_HOMA_IR$p.adj.signif[i]))
  
}


###########################################################
# repeat  for HOMA_B
###########################################################



data_HOMA_B=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$HOMA_B,DF_blood_horm_food$ID))
colnames(data_HOMA_B)=c("Visit","HOMA_B","ID")
data_HOMA_B$Visit=factor(data_HOMA_B$Visit,levels = ord)
data_HOMA_B$HOMA_B=as.numeric(data_HOMA_B$HOMA_B)
FT_HOMA_B=friedman.test(data_HOMA_B$HOMA_B,groups = data_HOMA_B$Visit,
                        blocks = data_HOMA_B$ID,data=data_HOMA_B)
text_FT_HOMA_B=(paste("Friedman Test","p =",round(FT_HOMA_B$p.value,4)))


WT_HOMA_B=data_HOMA_B %>%
  wilcox_test(HOMA_B ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_HOMA_B$p.adj=round(WT_HOMA_B$p.adj,6)
WT_HOMA_B <- WT_HOMA_B %>% add_xy_position(x = "Visit",step.increase = 0.60)
ggboxplot(data_HOMA_B, x = "Visit", y = "HOMA_B",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="HOMA-B",x="Weeks", y = "HOMA-B",subtitle = text_FT_HOMA_B )+
  stat_pvalue_manual(WT_HOMA_B,label="p.adj",tip.length = 0.01)


res_HOMA_B=matrix(NA,nrow=nrow(WT_HOMA_B),ncol=9)
for(i in 1:nrow(WT_HOMA_B)){
  
  testdata_HOMA_B=cbind(data_HOMA_B[data_HOMA_B$Visit==WT_HOMA_B$group1[i],"HOMA_B"],data_HOMA_B[data_HOMA_B$Visit==WT_HOMA_B$group2[i],"HOMA_B"])
  testdata_HOMA_B=na.omit(testdata_HOMA_B)
  res_HOMA_B[i,]=print(c(WT_HOMA_B$.y.[i],WT_HOMA_B$group1[i],WT_HOMA_B$group2[i],
                         WT_HOMA_B$n1[i],
                         WT_HOMA_B$n2[i],"diff between means",
                         round(mean(testdata_HOMA_B[,1]-testdata_HOMA_B[,2]),4),
                         WT_HOMA_B$p.adj[i],WT_HOMA_B$p.adj.signif[i]))
  
}


###########################################################
# repeat  for GL
###########################################################



data_GL=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$GL,DF_blood_horm_food$ID))
colnames(data_GL)=c("Visit","GL","ID")
data_GL$Visit=factor(data_GL$Visit,levels = ord)
data_GL$GL=as.numeric(data_GL$GL)
FT_GL=friedman.test(data_GL$GL,groups = data_GL$Visit,
                    blocks = data_GL$ID,data=data_GL)
text_FT_GL=(paste("Friedman Test","p =",round(FT_GL$p.value,4)))


WT_GL=data_GL %>%
  wilcox_test(GL ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_GL$p.adj=round(WT_GL$p.adj,6)
WT_GL <- WT_GL %>% add_xy_position(x = "Visit",step.increase = 0.60)
ggboxplot(data_GL, x = "Visit", y = "GL",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="GL",x="Weeks", y = "GL",subtitle = text_FT_GL )+
  stat_pvalue_manual(WT_GL,label="p.adj",tip.length = 0.01)



res_GL=matrix(NA,nrow=nrow(WT_GL),ncol=9)
for(i in 1:nrow(WT_GL)){
  
  testdata_GL=cbind(data_GL[data_GL$Visit==WT_GL$group1[i],"GL"],data_GL[data_GL$Visit==WT_GL$group2[i],"GL"])
  testdata_GL=na.omit(testdata_GL)
  res_GL[i,]=print(c(WT_GL$.y.[i],WT_GL$group1[i],WT_GL$group2[i],WT_GL$n1[i],
                     WT_GL$n2[i],"diff between means",
                     round(mean(testdata_GL[,1]-testdata_GL[,2]),4),
                     WT_GL$p.adj[i],WT_GL$p.adj.signif[i]))
  
}
###########################################################
# repeat  for COL
###########################################################



data_COL=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$COL,DF_blood_horm_food$ID))
colnames(data_COL)=c("Visit","COL","ID")
data_COL$Visit=factor(data_COL$Visit,levels = ord)
data_COL$COL=as.numeric(data_COL$COL)
FT_COL=friedman.test(data_COL$COL,groups = data_COL$Visit,
                     blocks = data_COL$ID,data=data_COL)
text_FT_COL=(paste("Friedman Test","p =",round(FT_COL$p.value,4)))


WT_COL=data_COL %>%
  wilcox_test(COL ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_COL$p.adj=round(WT_COL$p.adj,6)
WT_COL <- WT_COL %>% add_xy_position(x = "Visit",step.increase = 0.60)
ggboxplot(data_COL, x = "Visit", y = "COL",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="COL",x="Weeks", y = "COL",subtitle = text_FT_COL )+
  stat_pvalue_manual(WT_COL,label="p.adj",tip.length = 0.01)

res_COL=matrix(NA,nrow=nrow(WT_COL),ncol=9)
for(i in 1:nrow(WT_COL)){
  
  testdata_COL=cbind(data_COL[data_COL$Visit==WT_COL$group1[i],"COL"],data_COL[data_COL$Visit==WT_COL$group2[i],"COL"])
  testdata_COL=na.omit(testdata_COL)
  res_COL[i,]=print(c(WT_COL$.y.[i],WT_COL$group1[i],WT_COL$group2[i],WT_COL$n1[i],
                      WT_COL$n2[i],"diff between means",
                      round(mean(testdata_COL[,1]-testdata_COL[,2]),4),
                      WT_COL$p.adj[i],WT_COL$p.adj.signif[i]))
  
}
###########################################################
# repeat  for HDL
###########################################################

data_HDL=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$HDL,DF_blood_horm_food$ID))
colnames(data_HDL)=c("Visit","HDL","ID")
data_HDL$Visit=factor(data_HDL$Visit,levels = ord)
data_HDL$HDL=as.numeric(data_HDL$HDL)
FT_HDL=friedman.test(data_HDL$HDL,groups = data_HDL$Visit,
                     blocks = data_HDL$ID,data=data_HDL)
text_FT_HDL=(paste("Friedman Test","p =",round(FT_HDL$p.value,4)))


WT_HDL=data_HDL %>%
  wilcox_test(HDL ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_HDL$p.adj=round(WT_HDL$p.adj,6)
WT_HDL <- WT_HDL %>% add_xy_position(x = "Visit",step.increase = 0.80)
ggboxplot(data_HDL, x = "Visit", y = "HDL",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="HDL",x="Weeks", y = "HDL",subtitle = text_FT_HDL )+
  stat_pvalue_manual(WT_HDL,label="p.adj",tip.length = 0.01)
res_HDL=matrix(NA,nrow=nrow(WT_HDL),ncol=9)

for(i in 1:nrow(WT_HDL)){
  
  testdata_HDL=cbind(data_HDL[data_HDL$Visit==WT_HDL$group1[i],"HDL"],data_HDL[data_HDL$Visit==WT_HDL$group2[i],"HDL"])
  testdata_HDL=na.omit(testdata_HDL)
  res_HDL[i,]=print(c(WT_HDL$.y.[i],WT_HDL$group1[i],WT_HDL$group2[i],WT_HDL$n1[i],
                      WT_HDL$n2[i],"diff between means",
                      round(mean(testdata_HDL[,1]-testdata_HDL[,2]),4),
                      WT_HDL$p.adj[i],WT_HDL$p.adj.signif[i]))
  
}
###########################################################
# repeat  for LDL_C
###########################################################


data_LDLC=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$LDLC,DF_blood_horm_food$ID))
colnames(data_LDLC)=c("Visit","LDLC","ID")
data_LDLC$Visit=factor(data_LDLC$Visit,levels = ord)
data_LDLC$LDLC=as.numeric(data_LDLC$LDLC)
FT_LDLC=friedman.test(data_LDLC$LDLC,groups = data_LDLC$Visit,
                      blocks = data_LDLC$ID,data=data_LDLC)
text_FT_LDLC=(paste("Friedman Test","p =",round(FT_LDLC$p.value,4)))


WT_LDLC=data_LDLC %>%
  wilcox_test(LDLC ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_LDLC$p.adj=round(WT_LDLC$p.adj,6)
WT_LDLC <- WT_LDLC %>% add_xy_position(x = "Visit",step.increase = 0.60)
ggboxplot(data_LDLC, x = "Visit", y = "LDLC",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="LDLC",x="Weeks", y = "LDLC",subtitle = text_FT_LDLC )+
  stat_pvalue_manual(WT_LDLC,label="p.adj",tip.length = 0.01)


res_LDLC=matrix(NA,nrow=nrow(WT_LDLC),ncol=9)
for(i in 1:nrow(WT_LDLC)){
  
  testdata_LDLC=cbind(data_LDLC[data_LDLC$Visit==WT_LDLC$group1[i],"LDLC"],data_LDLC[data_LDLC$Visit==WT_LDLC$group2[i],"LDLC"])
  testdata_LDLC=na.omit(testdata_LDLC)
  res_LDLC[i,]=print(c(WT_LDLC$.y.[i],WT_LDLC$group1[i],WT_LDLC$group2[i],WT_LDLC$n1[i],
                       WT_LDLC$n2[i],"diff between means",
                       round(mean(testdata_LDLC[,1]-testdata_LDLC[,2]),4),
                       WT_LDLC$p.adj[i],WT_LDLC$p.adj.signif[i]))
  
}
###########################################################
# repeat  for TRI
###########################################################


data_TRI=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$TRI,DF_blood_horm_food$ID))
colnames(data_TRI)=c("Visit","TRI","ID")
data_TRI$Visit=factor(data_TRI$Visit,levels = ord)
data_TRI$TRI=as.numeric(data_TRI$TRI)
FT_TRI=friedman.test(data_TRI$TRI,groups = data_TRI$Visit,
                     blocks = data_TRI$ID,data=data_TRI)
text_FT_TRI=(paste("Friedman Test","p =",round(FT_TRI$p.value,4)))


WT_TRI=data_TRI %>%
  wilcox_test(TRI ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_TRI$p.adj=round(WT_TRI$p.adj,6)
WT_TRI <- WT_TRI %>% add_xy_position(x = "Visit",step.increase = 0.40)
ggboxplot(data_TRI, x = "Visit", y = "TRI",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="TRI",x="Weeks", y = "TRI",subtitle = text_FT_TRI )+
  stat_pvalue_manual(WT_TRI,label="p.adj",tip.length = 0.01)


res_TRI=matrix(NA,nrow=nrow(WT_TRI),ncol=9)
for(i in 1:nrow(WT_TRI)){
  
  testdata_TRI=cbind(data_TRI[data_TRI$Visit==WT_TRI$group1[i],"TRI"],data_TRI[data_TRI$Visit==WT_TRI$group2[i],"TRI"])
  testdata_TRI=na.omit(testdata_TRI)
  res_TRI[i,]=print(c(WT_TRI$.y.[i],WT_TRI$group1[i],WT_TRI$group2[i],WT_TRI$n1[i],
                      WT_TRI$n2[i],"diff between means",
                      round(mean(testdata_TRI[,1]-testdata_TRI[,2]),4),
                      WT_TRI$p.adj[i],WT_TRI$p.adj.signif[i]))
  
}
###########################################################
# repeat  for AST
###########################################################


data_AST=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$AST,DF_blood_horm_food$ID))
colnames(data_AST)=c("Visit","AST","ID")
data_AST$Visit=factor(data_AST$Visit,levels = ord)
data_AST$AST=as.numeric(data_AST$AST)
FT_AST=friedman.test(data_AST$AST,groups = data_AST$Visit,
                     blocks = data_AST$ID,data=data_AST)
text_FT_AST=(paste("Friedman Test","p =",round(FT_AST$p.value,4)))


WT_AST=data_AST %>%
  wilcox_test(AST ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_AST$p.adj=round(WT_AST$p.adj,6)
WT_AST <- WT_AST %>% add_xy_position(x = "Visit",step.increase = 0.30)
ggboxplot(data_AST, x = "Visit", y = "AST",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="AST",x="Weeks", y = "AST",subtitle = text_FT_AST )+
  stat_pvalue_manual(WT_AST,label="p.adj",tip.length = 0.01)

res_AST=matrix(NA,nrow=nrow(WT_AST),ncol=9)
for(i in 1:nrow(WT_AST)){
  
  testdata_AST=cbind(data_AST[data_AST$Visit==WT_AST$group1[i],"AST"],data_AST[data_AST$Visit==WT_AST$group2[i],"AST"])
  testdata_AST=na.omit(testdata_AST)
  res_AST[i,]=print(c(WT_AST$.y.[i],WT_AST$group1[i],WT_AST$group2[i],WT_AST$n1[i],
                      WT_AST$n2[i],"diff between means",
                      round(mean(testdata_AST[,1]-testdata_AST[,2]),4),
                      WT_AST$p.adj[i],WT_AST$p.adj.signif[i]))
  
}

###########################################################
# repeat  for ALT
###########################################################


data_ALT=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$ALT,DF_blood_horm_food$ID))
colnames(data_ALT)=c("Visit","ALT","ID")
data_ALT$Visit=factor(data_ALT$Visit,levels = ord)
data_ALT$ALT=as.numeric(data_ALT$ALT)
FT_ALT=friedman.test(data_ALT$ALT,groups = data_ALT$Visit,
                     blocks = data_ALT$ID,data=data_ALT)
text_FT_ALT=(paste("Friedman Test","p =",round(FT_ALT$p.value,4)))


WT_ALT=data_ALT %>%
  wilcox_test(ALT ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_ALT$p.adj=round(WT_ALT$p.adj,6)
WT_ALT <- WT_ALT %>% add_xy_position(x = "Visit",step.increase = 0.60)
ggboxplot(data_ALT, x = "Visit", y = "ALT",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="ALT",x="Weeks", y = "ALT",subtitle = text_FT_ALT )+
  stat_pvalue_manual(WT_ALT,label="p.adj",tip.length = 0.01)

res_ALT=matrix(NA,nrow=nrow(WT_ALT),ncol=9)
for(i in 1:nrow(WT_ALT)){
  
  testdata_ALT=cbind(data_ALT[data_ALT$Visit==WT_ALT$group1[i],"ALT"],data_ALT[data_ALT$Visit==WT_ALT$group2[i],"ALT"])
  testdata_ALT=na.omit(testdata_ALT)
  res_ALT[i,]=print(c(WT_ALT$.y.[i],WT_ALT$group1[i],WT_ALT$group2[i],WT_ALT$n1[i],
                      WT_ALT$n2[i],"diff between means",
                      round(mean(testdata_ALT[,1]-testdata_ALT[,2]),4),
                      WT_ALT$p.adj[i],WT_ALT$p.adj.signif[i]))
  
}


###########################################################
# repeat  for BES17
###########################################################




data_BES17=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$BES17,DF_blood_horm_food$ID))
colnames(data_BES17)=c("Visit","BES17","ID")
data_BES17$Visit=factor(data_BES17$Visit,levels = ord)
data_BES17$BES17=as.numeric(data_BES17$BES17)
FT_BES17=friedman.test(data_BES17$BES17,groups = data_BES17$Visit,
                       blocks = data_BES17$ID,data=data_BES17)
text_FT_BES17=(paste("Friedman Test","p =",round(FT_BES17$p.value,4)))


WT_BES17=data_BES17 %>%
  wilcox_test(BES17 ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_BES17$p.adj=round(WT_BES17$p.adj,6)
WT_BES17 <- WT_BES17 %>% add_xy_position(x = "Visit",step.increase = 0.10)
ggboxplot(data_BES17, x = "Visit", y = "BES17",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="BES17",x="Weeks", y = "BES17",subtitle = text_FT_BES17 )+
  stat_pvalue_manual(WT_BES17,label="p.adj",tip.length = 0.01)


res_BES17=matrix(NA,nrow=nrow(WT_BES17),ncol=9)
for(i in 1:nrow(WT_BES17)){
  
  testdata_BES17=cbind(data_BES17[data_BES17$Visit==WT_BES17$group1[i],"BES17"],data_BES17[data_BES17$Visit==WT_BES17$group2[i],"BES17"])
  testdata_BES17=na.omit(testdata_BES17)
  res_BES17[i,]=print(c(WT_BES17$.y.[i],WT_BES17$group1[i],WT_BES17$group2[i],WT_BES17$n1[i],
                        WT_BES17$n2[i],"diff between means",
                        round(mean(testdata_BES17[,1]-testdata_BES17[,2]),4),
                        WT_BES17$p.adj[i],WT_BES17$p.adj.signif[i]))
  
}

###########################################################
# repeat  for PROG
###########################################################





data_PROG=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$PROG,DF_blood_horm_food$ID))
colnames(data_PROG)=c("Visit","PROG","ID")
data_PROG$Visit=factor(data_PROG$Visit,levels = ord)
data_PROG$PROG=as.numeric(data_PROG$PROG)
FT_PROG=friedman.test(data_PROG$PROG,groups = data_PROG$Visit,
                      blocks = data_PROG$ID,data=data_PROG)
text_FT_PROG=(paste("Friedman Test","p =",round(FT_PROG$p.value,4)))


WT_PROG=data_PROG %>%
  wilcox_test(PROG ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_PROG$p.adj=round(WT_PROG$p.adj,6)
WT_PROG <- WT_PROG %>% add_xy_position(x = "Visit",step.increase = 0.10)
ggboxplot(data_PROG, x = "Visit", y = "PROG",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="PROG",x="Weeks", y = "PROG",subtitle = text_FT_PROG )+
  stat_pvalue_manual(WT_PROG,label="p.adj",tip.length = 0.01)


res_PROG=matrix(NA,nrow=nrow(WT_PROG),ncol=9)
for(i in 1:nrow(WT_PROG)){
  
  testdata_PROG=cbind(data_PROG[data_PROG$Visit==WT_PROG$group1[i],"PROG"],data_PROG[data_PROG$Visit==WT_PROG$group2[i],"PROG"])
  testdata_PROG=na.omit(testdata_PROG)
  res_PROG[i,]=print(c(WT_PROG$.y.[i],WT_PROG$group1[i],WT_PROG$group2[i],WT_PROG$n1[i],
                       WT_PROG$n2[i],"diff between means",
                       round(mean(testdata_PROG[,1]-testdata_PROG[,2]),4),
                       WT_PROG$p.adj[i],WT_PROG$p.adj.signif[i]))
  
}

###########################################################




############################################################
# repeat  for LH
###########################################################




data_LH=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$LH,DF_blood_horm_food$ID))
colnames(data_LH)=c("Visit","LH","ID")
data_LH$Visit=factor(data_LH$Visit,levels = ord)
data_LH$LH=as.numeric(data_LH$LH)
FT_LH=friedman.test(data_LH$LH,groups = data_LH$Visit,
                    blocks = data_LH$ID,data=data_LH)
text_FT_LH=(paste("Friedman Test","p =",round(FT_LH$p.value,4)))


WT_LH=data_LH %>%
  wilcox_test(LH ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_LH$p.adj=round(WT_LH$p.adj,6)
WT_LH <- WT_LH %>% add_xy_position(x = "Visit",step.increase = 0.30)
ggboxplot(data_LH, x = "Visit", y = "LH",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="LH",x="Weeks", y = "LH",subtitle = text_FT_LH )+
  stat_pvalue_manual(WT_LH,label="p.adj",tip.length = 0.01)

res_LH=matrix(NA,nrow=nrow(WT_LH),ncol=9)
for(i in 1:nrow(WT_LH)){
  
  testdata_LH=cbind(data_LH[data_LH$Visit==WT_LH$group1[i],"LH"],data_LH[data_LH$Visit==WT_LH$group2[i],"LH"])
  testdata_LH=na.omit(testdata_LH)
  res_LH[i,]=print(c(WT_LH$.y.[i],WT_LH$group1[i],WT_LH$group2[i],WT_LH$n1[i],
                     WT_LH$n2[i],"diff between means",
                     round(mean(testdata_LH[,1]-testdata_LH[,2]),4),
                     WT_LH$p.adj[i],WT_LH$p.adj.signif[i]))
  
}
###########################################################






###########################################################
# repeat  for FSH
###########################################################




data_FSH=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$FSH,DF_blood_horm_food$ID))
colnames(data_FSH)=c("Visit","FSH","ID")
data_FSH$Visit=factor(data_FSH$Visit,levels = ord)
data_FSH$FSH=as.numeric(data_FSH$FSH)
FT_FSH=friedman.test(data_FSH$FSH,groups = data_FSH$Visit,
                     blocks = data_FSH$ID,data=data_FSH)
text_FT_FSH=(paste("Friedman Test","p =",round(FT_FSH$p.value,4)))


WT_FSH=data_FSH %>%
  wilcox_test(FSH ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_FSH$p.adj=round(WT_FSH$p.adj,6)
WT_FSH <- WT_FSH %>% add_xy_position(x = "Visit",step.increase = 0.30)
ggboxplot(data_FSH, x = "Visit", y = "FSH",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="FSH",x="Weeks", y = "FSH",subtitle = text_FT_FSH )+
  stat_pvalue_manual(WT_FSH,label="p.adj",tip.length = 0.01) 

res_FSH=matrix(NA,nrow=nrow(WT_FSH),ncol=9)
for(i in 1:nrow(WT_FSH)){
  
  testdata_FSH=cbind(data_FSH[data_FSH$Visit==WT_FSH$group1[i],"FSH"],data_FSH[data_FSH$Visit==WT_FSH$group2[i],"FSH"])
  testdata_FSH=na.omit(testdata_FSH)
  res_FSH[i,]=print(c(WT_FSH$.y.[i],WT_FSH$group1[i],WT_FSH$group2[i],WT_FSH$n1[i],
                      WT_FSH$n2[i],"diff between means",
                      round(mean(testdata_FSH[,1]-testdata_FSH[,2]),4),
                      WT_FSH$p.adj[i],WT_FSH$p.adj.signif[i]))
  
}
###########################################################


###########################################################
# repeat  for INS
###########################################################




data_INS=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$INS,DF_blood_horm_food$ID))
colnames(data_INS)=c("Visit","INS","ID")
data_INS$Visit=factor(data_INS$Visit,levels = ord)
data_INS$INS=as.numeric(data_INS$INS)
FT_INS=friedman.test(data_INS$INS,groups = data_INS$Visit,
                     blocks = data_INS$ID,data=data_INS)
text_FT_INS=(paste("Friedman Test","p =",round(FT_INS$p.value,4)))


WT_INS=data_INS %>%
  wilcox_test(INS ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_INS$p.adj=round(WT_INS$p.adj,6)
WT_INS <- WT_INS %>% add_xy_position(x = "Visit",step.increase = 0.60)
ggboxplot(data_INS, x = "Visit", y = "INS",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="INS",x="Weeks", y = "INS",subtitle = text_FT_INS )+
  stat_pvalue_manual(WT_INS,label="p.adj",tip.length = 0.01)


res_INS=matrix(NA,nrow=nrow(WT_INS),ncol=9)
for(i in 1:nrow(WT_INS)){
  
  testdata_INS=cbind(data_INS[data_INS$Visit==WT_INS$group1[i],"INS"],data_INS[data_INS$Visit==WT_INS$group2[i],"INS"])
  testdata_INS=na.omit(testdata_INS)
  res_INS[i,]=print(c(WT_INS$.y.[i],WT_INS$group1[i],WT_INS$group2[i],WT_INS$n1[i],
                      WT_INS$n2[i],"diff between means",
                      round(mean(testdata_INS[,1]-testdata_INS[,2]),4),
                      WT_INS$p.adj[i],WT_INS$p.adj.signif[i]))
  
}

###########################################################
# repeat  for PRL
###########################################################




data_PRL=as.data.frame(cbind(DF_blood_horm_food$Visit,DF_blood_horm_food$PRL,DF_blood_horm_food$ID))
colnames(data_PRL)=c("Visit","PRL","ID")
data_PRL$Visit=factor(data_PRL$Visit,levels = ord)
data_PRL$PRL=as.numeric(data_PRL$PRL)
FT_PRL=friedman.test(data_PRL$PRL,groups = data_PRL$Visit,
                     blocks = data_PRL$ID,data=data_PRL)
text_FT_PRL=(paste("Friedman Test","p =",round(FT_PRL$p.value,4)))


WT_PRL=data_PRL %>%
  wilcox_test(PRL ~ Visit,
              paired=T, p.adjust.method = "bonferroni" )
WT_PRL$p.adj=round(WT_PRL$p.adj,6)
WT_PRL <- WT_PRL %>% add_xy_position(x = "Visit",step.increase = 0.20)
ggboxplot(data_PRL, x = "Visit", y = "PRL",
          color = "Visit", palette = "jco",add = "jitter" )+
  labs(title="PRL",x="Weeks", y = "PRL",subtitle = text_FT_PRL )+
  stat_pvalue_manual(WT_PRL,label="p.adj",tip.length = 0.01)
###########################################################

res_PRL=matrix(NA,nrow=nrow(WT_PRL),ncol=9)
for(i in 1:nrow(WT_PRL)){
  
  testdata_PRL=cbind(data_PRL[data_PRL$Visit==WT_PRL$group1[i],"PRL"],data_PRL[data_PRL$Visit==WT_PRL$group2[i],"PRL"])
  testdata_PRL=na.omit(testdata_PRL)
  res_PRL[i,]=print(c(WT_PRL$.y.[i],WT_PRL$group1[i],WT_PRL$group2[i],WT_PRL$n1[i],WT_PRL$n2[i],"diff tra medie",
                      round(mean(testdata_PRL[,1]-testdata_PRL[,2]),4),
                      WT_PRL$p.adj[i],WT_PRL$p.adj.signif[i]))
  
}


###########################################################
# now merge all results for the quantative traits analyzed above
###########################################################


res_TOT=rbind(res_HOMA_B,res_HOMA_IR,
              res_GL,res_PROG,res_BES17,res_COL,res_HDL,res_TRI,
              res_FSH,res_AST,res_ALT, res_LDLC,res_INS,res_PRL,res_LH,
              res_FSH)
colnames(res_TOT)=c("variable","Week ref 1","Week ref 2","n ref 1","n ref 2","res","mean diff","pvalue","signif.")


##write results to a csv file

write.csv(res_TOT,file="results_all_traits.csv",quote=FALSE, na="NA")



###########################################################
# Cathegorize Bristol Stool Case in 3 classes and Apply a wilcox test
###########################################################


DF_blood_horm_food$bristolstoolscale_CAT <- cut(DF_blood_horm_food$bristolstoolscale,
                                       breaks=c(0, 2, 4, 7),
                                       labels=c('1-2', '3-4', '5-6-7'))




DF_blood_horm_food$bristolstoolscale_CAT=as.numeric(DF_blood_horm_food$bristolstoolscale_CAT)
WT_bristol=DF_blood_horm_food[,-1] %>%
  wilcox_test(bristolstoolscale_CAT ~ Weeks,
              paired=T, p.adjust.method = "holm", comparisons = list(c("1", "2"), c("2", "3"),c("3", "4") ))
WT_bristol$p.adj=round(WT_bristol$p.adj,6)
WT_bristol <- WT_bristol %>% add_xy_position(x = "bristolstoolscale_CAT",step.increase = 0.10)

WT_bristol$xmax[3]=4

ggboxplot(DF_blood_horm_food, x = "Weeks", y = "bristolstoolscale_CAT",
          color = "Weeks", palette = "jco",add = "jitter" )+
  labs(title="Bristol Stool Scale",x="Weeks", y = "Bristol Cathegories")+
  stat_pvalue_manual(WT_bristol,label="p.adj",tip.length = 0.7)



############################################################
# Performe Correlation Analisis (only with Hormones and other blood traits using Spearman correlation, pairwise t test adjusted with Holm
###########################################################


DF_BH_1w=as.matrix(filter(DF_blood_horm_food[,c("GL","COL","HDL","LDLC","AST","ALT","PROG","FSH","BES17","PRL", "INS","LH","HOMA_IR","HOMA_B",
                                             "Weeks" )],Weeks=="1"))
DF_BH_2w=as.matrix(filter(DF_blood_horm_food[,c("GL","COL","HDL","LDLC","AST","ALT","PROG","FSH","BES17","PRL","INS","LH","HOMA_IR","HOMA_B",
                                             "Weeks" )],Weeks=="2"))
DF_BH_3w=as.matrix(filter(DF_blood_horm_food[,c("GL","COL","HDL","LDLC","AST","ALT","PROG","FSH","BES17","PRL","INS","LH","HOMA_IR","HOMA_B",
                                             "Weeks" )],Weeks=="3"))
DF_BH_4w=as.matrix(filter(DF_blood_horm_food[,c("GL","COL","HDL","LDLC","AST","ALT","PROG","FSH","BES17","PRL","INS","LH","HOMA_IR","HOMA_B",
                                             "Weeks" )],Weeks=="4"))

DF_BH_1w=DF_BH_1w[,-which(colnames(DF_BH_1w)=="Weeks")]
DF_BH_2w=DF_BH_2w[,-which(colnames(DF_BH_2w)=="Weeks")]
DF_BH_3w=DF_BH_3w[,-which(colnames(DF_BH_3w)=="Weeks")]
DF_BH_4w=DF_BH_4w[,-which(colnames(DF_BH_4w)=="Weeks")]



#####################
#Process traits of the first Week 
#####################

cor_mat_1w_complete=cor(DF_BH_1w,DF_BH_1w,use="pairwise.complete.obs",method="spearman")

# Apply corr.test function
cor_test_mat_1w_complete <- corr.test(DF_BH_1w,method="spearman",use="pairwise.complete.obs",adjust="holm")$p   


label_sig=c("*","**","***")
# plot matrix
corrplot::corrplot(cor_mat_1w_complete,method="square", title= "Spearman Correlation Matrix 1w ***=.01, **=.05, *=0.10",mar=c(0,0,1,0),
                   p.mat = cor_test_mat_1w_complete, insig = "label_sig",sig.level = c(.01, .05, .10), pch.cex = 0.8, pch.col = "black",tl.cex=0.8)


#######
# remove hashtag from the next two rows for saving the file in a latex -type table

# print(xtable(cor_mat_1w_complete,type="latex"), file = "cor_mat_1w_complete.tex")
# print(xtable(cor_test_mat_1w_complete,type="latex"), file = "cor_test_mat_1w_complete.tex")

#####################
#Process  traits of the second Week 
#####################

cor_mat_2w_complete=cor(DF_BH_2w,DF_BH_2w,use="pairwise.complete.obs",method="spearman")
cor_test_mat_2w_complete <- corr.test(DF_BH_2w,method="spearman",use="pairwise.complete.obs",adjust="holm")$p   # Apply corr.test function



corrplot::corrplot(cor_mat_2w_complete,method="square", title= "Spearman Correlation Matrix 2w ***=.01, **=.05, *=0.10",mar=c(0,0,1,0),
                   p.mat = cor_test_mat_2w_complete, insig = "label_sig",sig.level = c(.01, .05, .10), pch.cex = 0.8, pch.col = "black",tl.cex=0.8)


# remove hashtag from the next two rows for saving the file in a latex -type table

# print(xtable(cor_mat_2w_complete,type="latex"), file = "cor_mat_2w_complete.tex")
# print(xtable(cor_test_mat_2w_complete,type="latex"), file = "cor_test_mat_2w_complete.tex")

#####################
# Process traits of the third Week 
#####################


cor_mat_3w_complete=cor(DF_BH_3w,DF_BH_3w,use="pairwise.complete.obs",method="spearman")
cor_test_mat_3w_complete <- corr.test(DF_BH_3w,method="spearman",use="pairwise.complete.obs",adjust="holm")$p   # Apply corr.test function



corrplot::corrplot(cor_mat_3w_complete,method="square", title= "Spearman Correlation Matrix 3w ***=.01, **=.05, *=0.10",mar=c(0,0,1,0),
                   p.mat = cor_test_mat_3w_complete, insig = "label_sig",sig.level = c(.01, .05, .10), pch.cex = 0.8, pch.col = "black",tl.cex=0.8)

#######
# remove hashtag from the next two rows for saving the file in a latex -type table
# print(xtable(cor_mat_3w_complete,type="latex"), file = "cor_mat_3w_complete.tex")
# print(xtable(cor_test_mat_3w_complete,type="latex"), file = "cor_test_mat_3w_complete.tex")


#####################
# Process traits of the fourth Week 
#####################

cor_mat_4w_complete=cor(DF_BH_4w,DF_BH_4w,use="pairwise.complete.obs",method="spearman")
cor_test_mat_4w_complete <- corr.test(DF_BH_4w,method="spearman",use="pairwise.complete.obs",adjust="holm")$p   # Apply corr.test function


corrplot::corrplot(cor_mat_4w_complete,method="square", title= "Spearman Correlation Matrix 4w ***=.01, **=.05, *=0.10",mar=c(0,0,1,0),
                   p.mat = cor_test_mat_4w_complete, insig = "label_sig",sig.level = c(.01, .05, .10), pch.cex = 0.8, pch.col = "black",tl.cex=0.8)

#######
# remove hashtag from the next two rows for saving the file in a latex -type table
# print(xtable(cor_mat_4w_complete,type="latex"), file = "cor_mat_4w_complete.tex")
# print(xtable(cor_test_mat_4w_complete,type="latex"), file = "cor_test_mat_4w_complete.tex")

